package com.example.localization

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Bottom Navigation
    val navHome: String,
    val navServers: String,
    val navSettings: String,

    // Home Screen
    val appTitle: String,
    val statusConnected: String,
    val statusDisconnected: String,
    val statusConnecting: String,
    val statusReconnecting: String,
    val tapToConnect: String,
    val tapToDisconnect: String,
    val tapToCancel: String,
    val optimalServer: String,
    val optimalServerDesc: String,
    val selectServerTitle: String,
    val download: String,
    val upload: String,
    val ping: String,
    val duration: String,
    val ipAddress: String,
    val protocolLabel: String,
    val connectionProtected: String,
    val notProtected: String,
    val freeAndFastBadge: String,

    // Servers / Locations Screen
    val serversTitle: String,
    val serversSubtitle: String,
    val searchPlaceholder: String,
    val refreshServers: String,
    val filterAll: String,
    val filterFast: String,
    val filterLowPing: String,
    val noServersFound: String,
    val serverCountFormat: String,

    // Settings Screen
    val settingsTitle: String,
    val settingsSubtitle: String,
    val vpnSecurityCategory: String,
    val autoConnectTitle: String,
    val autoConnectSubtitle: String,
    val killSwitchTitle: String,
    val killSwitchSubtitle: String,
    val dnsLeakTitle: String,
    val dnsLeakSubtitle: String,
    val notificationsTitle: String,
    val notificationsSubtitle: String,
    val preferencesCategory: String,
    val protocolTitle: String,
    val languageTitle: String,
    val appearanceTitle: String,
    val appearanceLight: String,
    val appearanceDark: String,
    val appearanceSystem: String,
    val chooseThemeTitle: String,
    val chooseThemeSubtitle: String,
    val advancedCategory: String,
    val connectionLogsTitle: String,
    val viewLiveLogs: String,
    val aboutAppTitle: String,
    val helpSupportTitle: String,
    val versionFree: String,

    // Compliance Category in Settings
    val complianceCategory: String,
    val privacyPolicyTitle: String,
    val privacyPolicySubtitle: String,
    val dataSafetyTitle: String,
    val dataSafetySubtitle: String,
    val vpnDisclosureTitle: String,
    val vpnDisclosureSubtitle: String,
    val appPermissionsTitle: String,
    val appPermissionsSubtitle: String,

    // Language Selector Dialog
    val chooseLanguageTitle: String,
    val chooseLanguageSubtitle: String,
    val applyLanguageBtn: String,
    val cancelBtn: String,
    val closeBtn: String,

    // Prominent Disclosure Dialog
    val disclosureTitle: String,
    val disclosureSubtitle: String,
    val disclosurePoint1Title: String,
    val disclosurePoint1Desc: String,
    val disclosurePoint2Title: String,
    val disclosurePoint2Desc: String,
    val disclosurePoint3Title: String,
    val disclosurePoint3Desc: String,
    val agreeAndContinueBtn: String,
    val viewPrivacyPolicyLink: String,
    val viewDataSafetyLink: String,

    // Privacy Policy Dialog
    val privacyPolicyHeader: String,
    val privacyZeroLogsTitle: String,
    val privacyZeroLogsDesc: String,
    val privacyVpnServiceTitle: String,
    val privacyVpnServiceDesc: String,
    val privacySecurityTitle: String,
    val privacySecurityDesc: String,
    val privacyNoSaleTitle: String,
    val privacyNoSaleDesc: String,

    // Data Safety Dialog
    val dataSafetyHeader: String,
    val dataSafetySubheader: String,
    val noDataCollected: String,
    val noDataShared: String,
    val encryptedInTransit: String,
    val overheadNoticeTitle: String,
    val overheadNoticeDesc: String,

    // Permissions Dialog
    val permissionsHeader: String,
    val permissionsSubheader: String,
    val permissionsIntro: String,
    val vpnKeyPermTitle: String,
    val vpnKeyPermStatus: String,
    val vpnKeyPermDesc: String,
    val notifPermTitle: String,
    val notifPermGranted: String,
    val notifPermRequired: String,
    val notifPermDesc: String,
    val grantPermBtn: String,
    val openSettingsBtn: String,

    // Onboarding Dialog
    val onboardingTitle: String,
    val onboardingSubtitle: String,
    val freeFeatureTitle: String,
    val freeFeatureSubtitle: String,
    val noRegFeatureTitle: String,
    val noRegFeatureSubtitle: String,
    val secureFeatureTitle: String,
    val secureFeatureSubtitle: String,
    val onboardingDisclaimer: String,
    val onboardingContinueBtn: String,

    // Connection Details Dialog
    val connectionDetailsTitle: String,
    val sessionStatsTitle: String,
    val serverDetailsTitle: String,
    val countryLabel: String,
    val uptimeLabel: String,

    // Dynamic messages & Toasts
    val connectedToFormat: String,
    val reconnectingFormat: String,
    val serversRefreshedFormat: String,
    val serversRefreshFailed: String,
    val customConfigImported: String,
    val vpnPermissionRequired: String,
    val logCopiedToClipboard: String,

    // Privacy Policy Details (all 6 sections)
    val privacyVerifiedBadgeTitle: String,
    val privacyVerifiedBadgeSubtitle: String,
    val privacySection1Title: String,
    val privacySection1Content: String,
    val privacySection2Title: String,
    val privacySection2Content: String,
    val privacySection3Title: String,
    val privacySection3Content: String,
    val privacySection4Title: String,
    val privacySection4Content: String,
    val privacySection5Title: String,
    val privacySection5Content: String,
    val privacySection6Title: String,
    val privacySection6Content: String,
    val privacyAcceptButton: String,

    // Data Safety Dialog items
    val dataSafetySummaryTitle: String,
    val dataCollectionTitle: String,
    val dataCollectionValue: String,
    val dataSharingTitle: String,
    val dataSharingValue: String,
    val dataTransitTitle: String,
    val dataTransitValue: String,
    val dataDeletionTitle: String,
    val dataDeletionValue: String,
    val dataCategoriesTitle: String,
    val catLocationTitle: String,
    val catLocationStatus: String,
    val catPersonalTitle: String,
    val catPersonalStatus: String,
    val catBrowsingTitle: String,
    val catBrowsingStatus: String,
    val catDeviceTitle: String,
    val catDeviceStatus: String,
    val catThroughputTitle: String,
    val catThroughputStatus: String,
    val dataImpactTitle: String,
    val dataImpactContent: String,

    // Permissions Dialog items
    val netPermTitle: String,
    val netPermStatus: String,
    val netPermDesc: String,

    // Logs Dialog
    val logsDialogTitle: String,
    val noLogsAvailable: String,
    val copyButton: String,
    val clearButton: String,

    // System Default Language
    val systemDefaultName: String,
    val systemDefaultSubtitle: String,

    // Additional UI component strings
    val filterFavorites: String,
    val noFavoritesFound: String,
    val udpFastLabel: String,
    val tcpStableLabel: String,
    val customConfigImportTitle: String,
    val customConfigTitle: String,
    val customConfigNamePlaceholder: String,
    val customConfigContentPlaceholder: String,
    val saveAndUseBtn: String,
    val freeGuaranteeBadge: String,
    val securityProtocolSettingsTitle: String,
    val favoriteServerAction: String,
    val selectedServerAction: String,
    val autoServerBadge: String
) {
    fun formatConnectedTo(country: String): String = connectedToFormat.format(country)
    fun formatReconnecting(serverName: String): String = reconnectingFormat.format(serverName)
    fun formatServersRefreshed(count: Int): String = serversRefreshedFormat.format(count)
}

val LocalAppStrings = compositionLocalOf { EnglishStrings }
val LocalAppLanguage = compositionLocalOf { AppLanguage.ENGLISH }

val EnglishStrings = AppStrings(
    navHome = "Home",
    navServers = "Servers",
    navSettings = "Settings",

    appTitle = "Ruvon VPN",
    statusConnected = "Connected & Secured",
    statusDisconnected = "Disconnected",
    statusConnecting = "Connecting…",
    statusReconnecting = "Switching Server…",
    tapToConnect = "Tap to Connect",
    tapToDisconnect = "Tap to Disconnect",
    tapToCancel = "Cancel",
    optimalServer = "Fastest Server (Auto)",
    optimalServerDesc = "Optimal location based on latency",
    selectServerTitle = "Select Location",
    download = "Download",
    upload = "Upload",
    ping = "Ping",
    duration = "Duration",
    ipAddress = "IP Address",
    protocolLabel = "Protocol",
    connectionProtected = "Your internet connection is encrypted",
    notProtected = "You are currently unprotected",
    freeAndFastBadge = "Free & Unlimited",

    serversTitle = "VPN Servers",
    serversSubtitle = "Global high-speed OpenVPN servers",
    searchPlaceholder = "Search by country or city…",
    refreshServers = "Refresh",
    filterAll = "All",
    filterFast = "Fastest",
    filterLowPing = "Low Ping",
    noServersFound = "No servers found matching your query",
    serverCountFormat = "%d servers available (1 per country)",

    settingsTitle = "Settings",
    settingsSubtitle = "Security, tunneling & preferences",
    vpnSecurityCategory = "VPN Security & Tunneling",
    autoConnectTitle = "Auto-connect",
    autoConnectSubtitle = "Connect automatically on app launch",
    killSwitchTitle = "Kill Switch",
    killSwitchSubtitle = "Block internet if VPN connection drops",
    dnsLeakTitle = "DNS Leak Protection",
    dnsLeakSubtitle = "Enforce private encrypted DNS queries",
    notificationsTitle = "Notifications",
    notificationsSubtitle = "Connection status & disconnect quick action",
    preferencesCategory = "Preferences",
    protocolTitle = "Protocol",
    languageTitle = "Language",
    appearanceTitle = "App Appearance",
    appearanceLight = "Light",
    appearanceDark = "Dark",
    appearanceSystem = "Follow System",
    chooseThemeTitle = "Choose Appearance",
    chooseThemeSubtitle = "Select light, dark, or system default theme",
    advancedCategory = "Advanced & Logs",
    connectionLogsTitle = "Connection Logs",
    viewLiveLogs = "View Live OpenVPN Logs",
    aboutAppTitle = "About Fast VPN",
    helpSupportTitle = "Help & Support",
    versionFree = "v1.0.0 (100% Free)",

    complianceCategory = "Privacy & Google Play Compliance",
    privacyPolicyTitle = "Privacy Policy",
    privacyPolicySubtitle = "Strict Zero-Logs Policy",
    dataSafetyTitle = "Data Safety & Security",
    dataSafetySubtitle = "Google Play Safety Standards",
    vpnDisclosureTitle = "VPN Service Disclosure",
    vpnDisclosureSubtitle = "VpnService Policy Compliance",
    appPermissionsTitle = "App Permissions & Transparency",
    appPermissionsSubtitle = "Permission controls and rationale",

    chooseLanguageTitle = "Choose Language",
    chooseLanguageSubtitle = "Select your preferred app display language",
    applyLanguageBtn = "Apply",
    cancelBtn = "Cancel",
    closeBtn = "Close",

    disclosureTitle = "VPN Service & Privacy Disclosure",
    disclosureSubtitle = "In accordance with Google Play VPN policies, here is how our service operates to protect your privacy before you connect.",
    disclosurePoint1Title = "Core Android VpnService Usage",
    disclosurePoint1Desc = "This app uses Android's VpnService exclusively to create a secure device-level encrypted tunnel that routes your traffic safely.",
    disclosurePoint2Title = "Strict Zero-Logs Guarantee",
    disclosurePoint2Desc = "We never track, store, or sell your browsing history, DNS queries, real IP address, or any personal data.",
    disclosurePoint3Title = "Ephemeral Session Traffic Stats",
    disclosurePoint3Desc = "Download and upload statistics are calculated locally in device RAM only during active sessions and cleared immediately upon disconnect.",
    agreeAndContinueBtn = "Agree & Continue",
    viewPrivacyPolicyLink = "📜 Privacy Policy",
    viewDataSafetyLink = "🛡️ Data Safety",

    privacyPolicyHeader = "Privacy Policy",
    privacyZeroLogsTitle = "1. Strict Zero-Logs Guarantee",
    privacyZeroLogsDesc = "We uphold a strict zero-logs commitment. We do NOT record, log, monitor, or store: your real IP address, DNS requests, visited websites, connection timestamps, or session content.",
    privacyVpnServiceTitle = "2. Google Play VpnService Compliance",
    privacyVpnServiceDesc = "Our app uses Android's official VpnService strictly as a secure encrypted tunnel. We do NOT inject ads, tamper with unencrypted traffic, or perform surveillance.",
    privacySecurityTitle = "3. End-to-End Encryption Standards",
    privacySecurityDesc = "All traffic passing through the tunnel is encrypted using OpenVPN with AES-256-GCM cipher and TLS 1.3 key exchange, shielding your traffic on public Wi-Fi networks.",
    privacyNoSaleTitle = "4. No Data Selling or Third-Party Sharing",
    privacyNoSaleDesc = "We do not sell, rent, monetize, or disclose any user information to data brokers, advertisers, or third parties.",

    dataSafetyHeader = "Data Safety & Security",
    dataSafetySubheader = "Transparency report aligned with Google Play Console requirements",
    noDataCollected = "No Data Collected",
    noDataShared = "No Data Shared",
    encryptedInTransit = "Encrypted in Transit",
    overheadNoticeTitle = "Understanding Data Overhead with VPN",
    overheadNoticeDesc = "Due to cryptographic headers and IP encapsulation, you may notice a 5-15% increase in cellular data usage. This is standard across all secure VPN protocols.",

    permissionsHeader = "App Permissions & Transparency",
    permissionsSubheader = "Minimal privilege policy compliance",
    permissionsIntro = "Our app requests only the minimum technical permissions required to provide a safe VPN tunnel.",
    vpnKeyPermTitle = "VPN Service Permission (VpnService)",
    vpnKeyPermStatus = "Standard System Permission",
    vpnKeyPermDesc = "Handled automatically via Android's secure confirmation dialog on first connection.",
    notifPermTitle = "Notification Permission (Foreground Service)",
    notifPermGranted = "Granted & Active",
    notifPermRequired = "Required for Status Bar",
    notifPermDesc = "Allows displaying a persistent notification to monitor tunnel status and disconnect instantly.",
    grantPermBtn = "Grant Permission",
    openSettingsBtn = "Open App Settings in Android",

    onboardingTitle = "Ruvon VPN",
    onboardingSubtitle = "Fast, simple, secure VPN. A more private and open internet for everyone.",
    freeFeatureTitle = "Free access",
    freeFeatureSubtitle = "No payment required. 100% free forever.",
    noRegFeatureTitle = "No registration & Zero logs",
    noRegFeatureSubtitle = "Start using instantly. No email or account needed.",
    secureFeatureTitle = "Secure connection",
    secureFeatureSubtitle = "Protect your online activity with AES-256.",
    onboardingDisclaimer = "By continuing, you accept our Privacy Policy & Data Safety standards.",
    onboardingContinueBtn = "Continue",

    connectionDetailsTitle = "Connection Details",
    sessionStatsTitle = "Session Statistics",
    serverDetailsTitle = "Server Details",
    countryLabel = "Country",
    uptimeLabel = "Uptime",

    connectedToFormat = "Connected to %s",
    reconnectingFormat = "Reconnecting to %s…",
    serversRefreshedFormat = "Successfully refreshed %d servers!",
    serversRefreshFailed = "Could not refresh live servers. Using fast bundled servers.",
    customConfigImported = "Custom configuration added and activated successfully.",
    vpnPermissionRequired = "VPN permission is required to connect to the server.",
    logCopiedToClipboard = "Logs copied to clipboard.",

    privacyVerifiedBadgeTitle = "Strict Zero-Logs Policy",
    privacyVerifiedBadgeSubtitle = "We never log, track, or share your browsing activity or personal data.",
    privacySection1Title = "1. Android VpnService Usage & Google Play Compliance",
    privacySection1Content = "The core functionality of this application relies exclusively on Android's VpnService API to establish an encrypted device-level tunnel. In compliance with Google Play Developer Program Policies:\n• VpnService is used strictly to encrypt your internet connection and route traffic through secure OpenVPN servers.\n• We never use VpnService to redirect, manipulate, or monetize traffic from other applications.\n• No advertisements are injected into your browsing traffic.",
    privacySection2Title = "2. Information We Never Collect (Zero-Logs Guarantee)",
    privacySection2Content = "Our network architecture operates with zero retention:\n• No Browsing History: We never see, record, or store websites you visit or apps you use.\n• No DNS Queries: Queries are resolved via private encrypted DNS with leak protection.\n• No Real IP Addresses: Your real IP address and precise geographical location are never logged.\n• No Traffic Content: All data passing through the tunnel is encrypted end-to-end.\n• No Personal Identifiers: No account registration, email address, or phone number is ever required.",
    privacySection3Title = "3. Encryption & Technical Security Standards",
    privacySection3Content = "All data tunnels are secured with industry-leading cryptographic standards:\n• OpenVPN protocol with military-grade AES-256-GCM cipher.\n• TLS 1.3 cryptographic handshake for secure session establishment.\n• Integrated Kill Switch preventing data leakage during unexpected connection drops.\n• DNS Leak Protection directing domain queries through encrypted resolvers.",
    privacySection4Title = "4. Real-time Session Metrics (In-Memory Only)",
    privacySection4Content = "Live download and upload speed counters and connection duration are calculated strictly within device volatile memory (RAM) during an active session to display real-time dashboard stats. They are never transmitted to any analytics server and are wiped completely the moment you disconnect.",
    privacySection5Title = "5. Third-Party Data Sharing & Advertising",
    privacySection5Content = "We strictly uphold a policy of never selling, renting, licensing, or sharing user data with advertisers, data brokers, or any third parties for any purpose whatsoever.",
    privacySection6Title = "6. User Rights & Contact",
    privacySection6Content = "Because we collect zero personal data, there are no persistent identifiable records on our servers to manage or delete. You retain complete freedom to disconnect or uninstall the application at any time.\nFor technical inquiries: support@fastvpn.app",
    privacyAcceptButton = "I Understand & Agree",

    dataSafetySummaryTitle = "Google Play Data Safety Declaration Summary",
    dataCollectionTitle = "Data Collection",
    dataCollectionValue = "None (0%)",
    dataSharingTitle = "Data Sharing",
    dataSharingValue = "Never (0%)",
    dataTransitTitle = "Encryption in Transit",
    dataTransitValue = "Fully Encrypted",
    dataDeletionTitle = "Data Deletion",
    dataDeletionValue = "No Stored Data",
    dataCategoriesTitle = "Data Categories Breakdown (Google Play)",
    catLocationTitle = "Precise Geographical Location",
    catLocationStatus = "Never accessed or logged",
    catPersonalTitle = "Personal Info (Name, Email, Phone)",
    catPersonalStatus = "Not requested or collected",
    catBrowsingTitle = "Browsing & Web Activity History",
    catBrowsingStatus = "Zero logs recorded",
    catDeviceTitle = "Device Identifiers (ID / Ad ID)",
    catDeviceStatus = "Never read or used for tracking",
    catThroughputTitle = "Live Traffic Throughput",
    catThroughputStatus = "In RAM only during connection",
    dataImpactTitle = "How does VPN affect data usage?",
    dataImpactContent = "• OpenVPN encryption adds a small security header (about 4–7% additional overhead) to each packet, which is standard for all secure VPN tunnels.\n• The application never downloads background files without your knowledge.\n• You can monitor your total transmitted and received bytes in real time directly on the main dashboard.",

    netPermTitle = "Internet & Network Access",
    netPermStatus = "Granted Automatically",
    netPermDesc = "Standard Android permission to download public server lists and transmit encrypted packets.",

    logsDialogTitle = "OpenVPN Live Logs",
    noLogsAvailable = "No connection logs yet…",
    copyButton = "Copy",
    clearButton = "Clear",

    systemDefaultName = "System Default",
    systemDefaultSubtitle = "Automatic based on device language",

    filterFavorites = "Favorites ⭐",
    noFavoritesFound = "No favorite servers added yet",
    udpFastLabel = "OpenVPN UDP (Fast)",
    tcpStableLabel = "OpenVPN TCP (Stable)",
    customConfigImportTitle = "Import OpenVPN config (.ovpn)",
    customConfigTitle = "Add Custom Server",
    customConfigNamePlaceholder = "Server name (e.g. My Private Server)",
    customConfigContentPlaceholder = "Paste .ovpn file contents here…",
    saveAndUseBtn = "Save & Use",
    freeGuaranteeBadge = "This app is 100% free with no subscriptions or paid plans",
    securityProtocolSettingsTitle = "Security & Protocol Settings",
    favoriteServerAction = "Favorite server",
    selectedServerAction = "Selected",
    autoServerBadge = "Auto"
)

val ArabicStrings = AppStrings(
    navHome = "الرئيسية",
    navServers = "الخوادم",
    navSettings = "الإعدادات",

    appTitle = "Ruvon VPN",
    statusConnected = "متصل بأمان",
    statusDisconnected = "غير متصل",
    statusConnecting = "جاري الاتصال…",
    statusReconnecting = "جاري التبديل للخادم الجديد…",
    tapToConnect = "انقر للاتصال",
    tapToDisconnect = "انقر لقطع الاتصال",
    tapToCancel = "إلغاء",
    optimalServer = "أسرع خادم (تلقائي)",
    optimalServerDesc = "الموقع الأفضل استناداً لسرعة الاستجابة",
    selectServerTitle = "اختيار الدولة",
    download = "تحميل",
    upload = "رفع",
    ping = "الاستجابة",
    duration = "المدة",
    ipAddress = "عنوان IP",
    protocolLabel = "البروتوكول",
    connectionProtected = "اتصال الإنترنت الخاص بك مشفر وآمن",
    notProtected = "أنت غير محمي حالياً",
    freeAndFastBadge = "مجاني وغير محدود",

    serversTitle = "قائمة خوادم الـ VPN",
    serversSubtitle = "خوادم OpenVPN مجانية وسريعة حول العالم",
    searchPlaceholder = "ابحث بالدولة أو المدينة…",
    refreshServers = "تحديث",
    filterAll = "الكل",
    filterFast = "الأسرع",
    filterLowPing = "استجابة ممتازة",
    noServersFound = "لا توجد خوادم مطابقة للبحث",
    serverCountFormat = "%d خادم متوفر (خادم واحد لكل دولة)",

    settingsTitle = "الإعدادات",
    settingsSubtitle = "الأمان، الاتصال وتفضيلات التطبيق",
    vpnSecurityCategory = "أمان وتشفير اتصال الـ VPN",
    autoConnectTitle = "الاتصال التلقائي",
    autoConnectSubtitle = "الاتصال تلقائياً عند فتح التطبيق",
    killSwitchTitle = "مفتاح الإيقاف التلقائي (Kill Switch)",
    killSwitchSubtitle = "حظر الإنترنت تلقائياً في حال انقطاع الـ VPN",
    dnsLeakTitle = "حماية تسرب DNS",
    dnsLeakSubtitle = "فرض استعلامات DNS خاصة ومشفرة دائماً",
    notificationsTitle = "الإشعارات والتنبيهات",
    notificationsSubtitle = "إشعار دائم لعرض السرعة وزر قطع الاتصال السريع",
    preferencesCategory = "التفضيلات واللغة",
    protocolTitle = "نوع البروتوكول",
    languageTitle = "لغة التطبيق",
    appearanceTitle = "مظهر التطبيق",
    appearanceLight = "فاتح",
    appearanceDark = "داكن (Dark Mode)",
    appearanceSystem = "حسب إعدادات النظام",
    chooseThemeTitle = "اختيار مظهر التطبيق",
    chooseThemeSubtitle = "حدد الوضع الفاتح أو الداكن أو حسب حالة الجهاز",
    advancedCategory = "متقدم وسجلات الاتصال",
    connectionLogsTitle = "سجلات الاتصال المباشرة",
    viewLiveLogs = "عرض سجلات OpenVPN اللحظية",
    aboutAppTitle = "حول تطبيق Fast VPN",
    helpSupportTitle = "المساعدة والدعم",
    versionFree = "v1.0.0 (مجاني 100%)",

    complianceCategory = "الخصوصية والامتثال لـ Google Play",
    privacyPolicyTitle = "سياسة الخصوصية",
    privacyPolicySubtitle = "سياسة صارمة لمنع السجلات",
    dataSafetyTitle = "أمان واستخدام البيانات",
    dataSafetySubtitle = "معايير سلامة بيانات Google Play",
    vpnDisclosureTitle = "إفصاح خدمة الـ VPN",
    vpnDisclosureSubtitle = "الامتثال لسياسة VpnService",
    appPermissionsTitle = "أذونات التطبيق والشفافية",
    appPermissionsSubtitle = "إدارة وتبرير الأذونات المطلوبة",

    chooseLanguageTitle = "اختر لغة التطبيق",
    chooseLanguageSubtitle = "حدد اللغة المفضلة لواجهات التطبيق",
    applyLanguageBtn = "تطبيق",
    cancelBtn = "إلغاء",
    closeBtn = "إغلاق",

    disclosureTitle = "إفصاح خدمة الـ VPN والخصوصية",
    disclosureSubtitle = "وفقاً لسياسات Google Play المتعلقة بخدمات VPN، نوضح لك طبيعة عمل الخدمة وكيفية حماية بياناتك قبل تفعيل الاتصال.",
    disclosurePoint1Title = "استخدام خدمة VpnService الأساسية",
    disclosurePoint1Desc = "يستخدم التطبيق واجهة VpnService من أندرويد فقط لإنشاء نفق تشفير آمن على مستوى الجهاز لحماية اتصالك وتوجيه البيانات بأمان.",
    disclosurePoint2Title = "سياسة صارمة لمنع السجلات (Zero-Logs)",
    disclosurePoint2Desc = "لا نسجل، لا نراقب، ولا نبيع سجل تصفحك أو استعلامات DNS أو عنوان IP الحقيقي الخاص بك أو أي بيانات شخصية.",
    disclosurePoint3Title = "إحصائيات الجلسة اللحظية",
    disclosurePoint3Desc = "يتم حساب سرعة التنزيل والرفع محلياً في ذاكرة الجهاز (RAM) فقط لعرضها أثناء الاتصال، ويتم مسحها فوراً عند قطع الاتصال.",
    agreeAndContinueBtn = "أوافق وأتابع (Agree & Continue)",
    viewPrivacyPolicyLink = "📜 سياسة الخصوصية",
    viewDataSafetyLink = "🛡️ أمان واستخدام البيانات",

    privacyPolicyHeader = "سياسة الخصوصية",
    privacyZeroLogsTitle = "1. سياسة صارمة لمنع السجلات (Zero-Logs)",
    privacyZeroLogsDesc = "نلتزم التزاماً كاملاً بعدم تسجيل أو مراقبة أو تخزين أي نشاط للمستخدم: لا نسجل عنوان IP الحقيقي، ولا استعلامات DNS، ولا المواقع التي تزورها، ولا أوقات الاتصال، ولا محتوى البيانات.",
    privacyVpnServiceTitle = "2. الامتثال لسياسات VpnService في Google Play",
    privacyVpnServiceDesc = "نستخدم VpnService الرسمية لأغراض الحماية والتشفير المشروع فقط، ولا نستخدم النفق للتلاعب بالحزم أو حقن الإعلانات أو جمع البيانات.",
    privacySecurityTitle = "3. معايير التشفير والأمان الفائق",
    privacySecurityDesc = "تشفير كامل لجميع البيانات عبر بروتوكول OpenVPN وخوارزمية AES-256-GCM وتبادل مفاتيح TLS 1.3 مع حماية تسرب DNS.",
    privacyNoSaleTitle = "4. عدم مشاركة أو بيع البيانات لأطراف ثالثة",
    privacyNoSaleDesc = "لا نقوم بمشاركة أو بيع أو تأجير أي بيانات لأطراف ثالثة أو شركات تسويق أو وسطاء بيانات نهائياً.",

    dataSafetyHeader = "أمان واستخدام البيانات (Data Safety)",
    dataSafetySubheader = "تقرير الشفافية الرسمي المتوافق مع متطلبات Google Play Console",
    noDataCollected = "لا يتم جمع أي بيانات",
    noDataShared = "لا يتم مشاركة أي بيانات",
    encryptedInTransit = "مشفر بالكامل أثناء النقل",
    overheadNoticeTitle = "تنويه حول استهلاك البيانات أثناء تشغيل الـ VPN",
    overheadNoticeDesc = "بسبب ترويسات التشفير الأمنية لكل حزمة، قد تلاحظ زيادة بنسبة 5-15% في استهلاك باقة الإنترنت، وهو أمر قياسي في جميع بروتوكولات الـ VPN الآمنة.",

    permissionsHeader = "أذونات التطبيق والشفافية",
    permissionsSubheader = "وفق معايير الحد الأدنى من الأذونات",
    permissionsIntro = "يطلب التطبيق فقط الأذونات الضرورية تقنياً لتشغيل نفق الـ VPN بأمان وفق سياسات Google Play.",
    vpnKeyPermTitle = "إذن خدمة الـ VPN (VpnService)",
    vpnKeyPermStatus = "إذن نظام معتمد",
    vpnKeyPermDesc = "يتم طلبه تلقائياً عبر نافذة حماية نظام Android عند أول اتصال لإنشاء النفق المشفر بأمان.",
    notifPermTitle = "إذن الإشعارات (Foreground Service)",
    notifPermGranted = "ممنوح ومفعل",
    notifPermRequired = "مطلوب لتنبيهات الاتصال",
    notifPermDesc = "مطلوب لإبقاء إشعار دائم في شريط الحالة أثناء عمل الـ VPN لتمكينك من متابعة سرعة النفق وإيقافه فوراً بنقرة واحدة.",
    grantPermBtn = "تفعيل الإذن",
    openSettingsBtn = "فتح إعدادات التطبيق في النظام",

    onboardingTitle = "Ruvon VPN",
    onboardingSubtitle = "تطبيق VPN سريع، بسيط وآمن لإنترنت مفتوح ومحمي للجميع.",
    freeFeatureTitle = "وصول مجاني 100%",
    freeFeatureSubtitle = "بدون أي رسوم أو اشتراكات شهرية.",
    noRegFeatureTitle = "بدون تسجيل وبدون سجلات",
    noRegFeatureSubtitle = "ابدأ الاستخدام فوراً بدون بريد أو حساب شخصي.",
    secureFeatureTitle = "اتصال مشفر وآمن",
    secureFeatureSubtitle = "حماية كاملة لنشاطك على الإنترنت بتشفير AES-256.",
    onboardingDisclaimer = "بالاستمرار، أنت توافق على سياسة الخصوصية ومعايير أمان البيانات.",
    onboardingContinueBtn = "متابعة",

    connectionDetailsTitle = "تفاصيل الاتصال",
    sessionStatsTitle = "إحصائيات الجلسة",
    serverDetailsTitle = "بيانات الخادم",
    countryLabel = "الدولة",
    uptimeLabel = "وقت التشغيل",

    connectedToFormat = "متصل بـ %s",
    reconnectingFormat = "جاري إعادة الاتصال بخادم %s...",
    serversRefreshedFormat = "تم تحديث %d خادم بنجاح!",
    serversRefreshFailed = "تعذر تحديث الخوادم مباشرة، تم استخدام الخوادم المدمجة السريعة.",
    customConfigImported = "تمت إضافة وتفعيل ملف التكوين المخصص بنجاح.",
    vpnPermissionRequired = "يلزم منح إذن الـ VPN للاتصال بالخادم.",
    logCopiedToClipboard = "تم نسخ السجل إلى الحافظة.",

    privacyVerifiedBadgeTitle = "سياسة صارمة لمنع السجلات (Zero-Logs Policy)",
    privacyVerifiedBadgeSubtitle = "لا نسجل، لا نراقب، ولا نشارك أي نشاط تصفح أو بيانات شخصية إطلاقاً.",
    privacySection1Title = "1. استخدام خدمة VpnService وفق معايير Google Play",
    privacySection1Content = "تعتمد الوظيفة الأساسية لهذا التطبيق حصرياً على واجهة برمجة تطبيقات VpnService من نظام Android لإنشاء نفق تشفير آمن على مستوى الجهاز. الغرض الوحيد من استخدام VpnService هو:\n• تأمين وتشفير اتصالك بالإنترنت أثناء استخدام شبكات Wi-Fi العامة أو غير الموثوقة.\n• توجيه حزم البيانات عبر خوادم OpenVPN مشفرة لحماية عنوان IP الأصلي الخاص بك.\n• لا نقوم بأي تلاعب في حركة المرور، ولا نقوم بحقن أي إعلانات، ولا نتدخل في أداء التطبيقات الأخرى.",
    privacySection2Title = "2. البيانات التي لا يتم جمعها إطلاقاً (عدم الاحتفاظ بالسجلات)",
    privacySection2Content = "نحن نؤمن بحق الخصوصية المطلق، لذا تم تصميم بنية التطبيق التقنية لعدم حفظ أو تخزين:\n• لا نسجل سجل التصفح، المواقع، أو التطبيقات التي تستخدمها.\n• لا نخزن استعلامات DNS (حيث يتم توجيهها مشفرة عبر DNS Leak Protection).\n• لا نسجل عنوان IP الحقيقي الخاص بك أو موقعك الجغرافي الدقيق.\n• لا نسجل محتوى البيانات المرسلة أو المستقبلة عبر النفق المشفر.\n• لا نطلب ولا نخزن أي معلومات شخصية (مثل الاسم أو البريد أو رقم الهاتف).",
    privacySection3Title = "3. التشفير والأمان التقني",
    privacySection3Content = "يتم تأمين جميع قنوات الاتصال باستخدام معايير التشفير الرائدة في الصناعة:\n• تشفير OpenVPN AES-256-GCM عسكري المستوى مع مفاتيح تبادل TLS 1.3.\n• ميزة مفتاح القفل (Kill Switch) لحجب البيانات عند أي انقطاع مفاجئ في الاتصال.\n• حماية تسرب استعلامات DNS لحظر رصد مزود خدمة الإنترنت لنشاطك.",
    privacySection4Title = "4. البيانات اللحظية المؤقتة (داخل الذاكرة العشوائية فقط)",
    privacySection4Content = "تُحسب سرعات التنزيل والرفع ومدة الجلسة لحظياً داخل الذاكرة العشوائية (RAM) للجهاز فقط أثناء الاتصال النشط، ولا تُرسل أبداً لأي خادم تحليلي، وتُمسح فوراً عند قطع الاتصال.",
    privacySection5Title = "5. عدم بيع أو مشاركة البيانات لأي طرف ثالث",
    privacySection5Content = "نلتزم التزاماً قاطعاً بعدم بيع أو تأجير أو مشاركة أو تداول أي بيانات خاصة بالمستخدمين مع شركات الإعلانات أو وسطاء البيانات أو أي جهات خارجية لأي غرض تجاري.",
    privacySection6Title = "6. حقوق المستخدم والتواصل",
    privacySection6Content = "نظراً لعدم جمع أي بيانات شخصية، لا توجد سجلات مرتبطة بك على خوادمنا. يمكنك دائماً التوقف عن استخدام التطبيق أو حذفه في أي وقت.\nللتواصل: support@fastvpn.app",
    privacyAcceptButton = "فهمت وموافق",

    dataSafetySummaryTitle = "ملخص إقرار أمان البيانات (Google Play Data Safety)",
    dataCollectionTitle = "جمع البيانات",
    dataCollectionValue = "لا يوجد (0%)",
    dataSharingTitle = "مشاركة البيانات",
    dataSharingValue = "لا تشارك (0%)",
    dataTransitTitle = "التشفير أثناء النقل",
    dataTransitValue = "مشفّر بالكامل",
    dataDeletionTitle = "حذف البيانات",
    dataDeletionValue = "لا توجد بيانات مخزنة",
    dataCategoriesTitle = "تفصيل فئات البيانات وفق تصنيفات Google Play",
    catLocationTitle = "الموقع الجغرافي الدقيق (Precise Location)",
    catLocationStatus = "غير مستخدم إطلاقاً",
    catPersonalTitle = "المعلومات الشخصية (الاسم، البريد، الهاتف)",
    catPersonalStatus = "غير مطلوبة ولا يتم جمعها",
    catBrowsingTitle = "سجل التصفح وسجل الويب (Web Browsing)",
    catBrowsingStatus = "صفر سجلات (Zero Logs)",
    catDeviceTitle = "معرفات الجهاز (Device ID / Advertising ID)",
    catDeviceStatus = "لا يتم قراءتها أو استخدامها للتتبع",
    catThroughputTitle = "حركة البيانات اللحظية (Live Throughput)",
    catThroughputStatus = "في ذاكرة RAM فقط أثناء الاتصال",
    dataImpactTitle = "كيف يؤثر الـ VPN على باقة الإنترنت؟",
    dataImpactContent = "• تشفير OpenVPN يضيف ترويسة أمان صغيرة (حوالي 4-7% حجم إضافي) لكل حزمة بيانات مشفرة، وهو المعيار العالمي لضمان الأمان.\n• لا يقوم التطبيق بتنزيل أي ملفات في الخلفية بدون علمك.\n• يمكنك مراقبة إجمالي البايتات المرسلة والمستقبلة بدقة مباشرة من لوحة التحكم الرئيسية.",

    netPermTitle = "الوصول للإنترنت والشبكة (Internet)",
    netPermStatus = "ممنوح تلقائياً",
    netPermDesc = "إذن قياسي لتنزيل قائمة الخوادم العامة وإرسال واستقبال حزم بيانات الإنترنت.",

    logsDialogTitle = "سجل أحداث OpenVPN",
    noLogsAvailable = "لا توجد سجلات اتصال حتى الآن…",
    copyButton = "نسخ",
    clearButton = "مسح",

    systemDefaultName = "افتراضي النظام (System)",
    systemDefaultSubtitle = "تلقائي حسب لغة الجهاز",

    filterFavorites = "المفضلة ⭐",
    noFavoritesFound = "لا توجد خوادم في المفضلة بعد",
    udpFastLabel = "OpenVPN UDP (أسرع)",
    tcpStableLabel = "OpenVPN TCP (أكثر استقراراً)",
    customConfigImportTitle = "استيراد ملف تكوين OpenVPN (.ovpn)",
    customConfigTitle = "إضافة خادم مخصص",
    customConfigNamePlaceholder = "اسم الخادم (مثال: سيرفري الخاص)",
    customConfigContentPlaceholder = "الصق محتوى ملف .ovpn هنا…",
    saveAndUseBtn = "حفظ واستخدام",
    freeGuaranteeBadge = "هذا التطبيق مجاني بالكامل بدون أي اشتراكات أو خطط مدفوعة",
    securityProtocolSettingsTitle = "إعدادات الأمان والبروتوكول",
    favoriteServerAction = "تفضيل الخادم",
    selectedServerAction = "محدد",
    autoServerBadge = "تلقائي"
)

val FrenchStrings = AppStrings(
    navHome = "Accueil",
    navServers = "Serveurs",
    navSettings = "Paramètres",

    appTitle = "Ruvon VPN",
    statusConnected = "Connecté et Sécurisé",
    statusDisconnected = "Déconnecté",
    statusConnecting = "Connexion en cours…",
    statusReconnecting = "Changement de serveur…",
    tapToConnect = "Appuyer pour se connecter",
    tapToDisconnect = "Appuyer pour déconnecter",
    tapToCancel = "Annuler",
    optimalServer = "Serveur le plus rapide (Auto)",
    optimalServerDesc = "Emplacement optimal selon la latence",
    selectServerTitle = "Choisir l'emplacement",
    download = "Téléchargement",
    upload = "Envoi",
    ping = "Ping",
    duration = "Durée",
    ipAddress = "Adresse IP",
    protocolLabel = "Protocole",
    connectionProtected = "Votre connexion est chiffrée et sécurisée",
    notProtected = "Vous n'êtes pas protégé actuellement",
    freeAndFastBadge = "Gratuit et Illimité",

    serversTitle = "Serveurs VPN",
    serversSubtitle = "Serveurs OpenVPN haut débit à travers le monde",
    searchPlaceholder = "Rechercher un pays ou une ville…",
    refreshServers = "Actualiser",
    filterAll = "Tous",
    filterFast = "Plus rapides",
    filterLowPing = "Faible latence",
    noServersFound = "Aucun serveur trouvé pour cette recherche",
    serverCountFormat = "%d serveurs disponibles (1 par pays)",

    settingsTitle = "Paramètres",
    settingsSubtitle = "Sécurité, tunneling et préférences",
    vpnSecurityCategory = "Sécurité et Tunneling VPN",
    autoConnectTitle = "Connexion automatique",
    autoConnectSubtitle = "Se connecter au lancement de l'application",
    killSwitchTitle = "Bouton d'arrêt d'urgence (Kill Switch)",
    killSwitchSubtitle = "Bloquer Internet en cas de coupure VPN",
    dnsLeakTitle = "Protection contre les fuites DNS",
    dnsLeakSubtitle = "Appliquer des requêtes DNS privées et chiffrées",
    notificationsTitle = "Notifications",
    notificationsSubtitle = "Statut de connexion et déconnexion rapide",
    preferencesCategory = "Préférences et Langue",
    protocolTitle = "Protocole",
    languageTitle = "Langue de l'application",
    appearanceTitle = "Apparence",
    appearanceLight = "Clair",
    appearanceDark = "Sombre",
    appearanceSystem = "Selon le système",
    chooseThemeTitle = "Choisir l'apparence",
    chooseThemeSubtitle = "Sélectionnez le mode clair, sombre ou système",
    advancedCategory = "Avancé et Journaux",
    connectionLogsTitle = "Journaux de connexion",
    viewLiveLogs = "Voir les journaux OpenVPN en direct",
    aboutAppTitle = "À propos de Fast VPN",
    helpSupportTitle = "Aide et Support",
    versionFree = "v1.0.0 (100% Gratuit)",

    complianceCategory = "Confidentialité et Conformité Google Play",
    privacyPolicyTitle = "Politique de confidentialité",
    privacyPolicySubtitle = "Politique stricte sans journaux (Zero-Logs)",
    dataSafetyTitle = "Sécurité et Utilisation des données",
    dataSafetySubtitle = "Normes de sécurité Google Play",
    vpnDisclosureTitle = "Divulgation du service VPN",
    vpnDisclosureSubtitle = "Conformité à la politique VpnService",
    appPermissionsTitle = "Autorisations et Transparence",
    appPermissionsSubtitle = "Gestion et justification des autorisations",

    chooseLanguageTitle = "Choisir la langue",
    chooseLanguageSubtitle = "Sélectionnez la langue d'affichage souhaitée",
    applyLanguageBtn = "Appliquer",
    cancelBtn = "Annuler",
    closeBtn = "Fermer",

    disclosureTitle = "Divulgation du service VPN et Confidentialité",
    disclosureSubtitle = "Conformément aux règles de Google Play pour les applications VPN, voici comment fonctionne notre service pour protéger votre vie privée avant la connexion.",
    disclosurePoint1Title = "Utilisation du service VpnService d'Android",
    disclosurePoint1Desc = "L'application utilise l'interface officielle VpnService d'Android uniquement pour établir un tunnel chiffré au niveau de l'appareil.",
    disclosurePoint2Title = "Garantie stricte sans journaux (Zero-Logs)",
    disclosurePoint2Desc = "Nous n'enregistrons, ne surveillons et ne vendons jamais votre historique de navigation, vos requêtes DNS, votre adresse IP réelle ou vos données personnelles.",
    disclosurePoint3Title = "Statistiques de trafic de session éphémères",
    disclosurePoint3Desc = "Les débits de téléchargement et d'envoi sont calculés localement dans la mémoire vive (RAM) uniquement pendant la session et supprimés à la déconnexion.",
    agreeAndContinueBtn = "Accepter et Continuer",
    viewPrivacyPolicyLink = "📜 Politique de confidentialité",
    viewDataSafetyLink = "🛡️ Sécurité des données",

    privacyPolicyHeader = "Politique de confidentialité",
    privacyZeroLogsTitle = "1. Engagement strict sans journaux (Zero-Logs)",
    privacyZeroLogsDesc = "Nous appliquons une politique stricte d'absence de journaux. Nous n'enregistrons, ne stockons ni ne surveillons votre adresse IP réelle, vos requêtes DNS, vos sites visités ou le contenu de vos échanges.",
    privacyVpnServiceTitle = "2. Conformité VpnService de Google Play",
    privacyVpnServiceDesc = "Notre application utilise le service officiel VpnService à des fins légitimes de chiffrement. Nous n'injectons aucune publicité et ne modifions pas votre trafic.",
    privacySecurityTitle = "3. Normes de chiffrement de haut niveau",
    privacySecurityDesc = "Tout le trafic est chiffré avec OpenVPN et l'algorithme AES-256-GCM avec échange de clés TLS 1.3 et protection contre les fuites DNS.",
    privacyNoSaleTitle = "4. Aucune vente ni partage de données avec des tiers",
    privacyNoSaleDesc = "Nous ne vendons, ne louons et ne transmettons aucune information utilisateur à des courtiers en données ou des tiers publicitaires.",

    dataSafetyHeader = "Sécurité des données (Data Safety)",
    dataSafetySubheader = "Rapport de transparence aligné sur les exigences de Google Play Console",
    noDataCollected = "Aucune donnée collectée",
    noDataShared = "Aucune donnée partagée",
    encryptedInTransit = "Chiffré en transit",
    overheadNoticeTitle = "Consommation de données avec le VPN",
    overheadNoticeDesc = "En raison des en-têtes de chiffrement et de l'encapsulation IP, vous pouvez observer une augmentation de 5 à 15 % de la consommation de données cellulaires, ce qui est standard pour les VPN sécurisés.",

    permissionsHeader = "Autorisations de l'application",
    permissionsSubheader = "Respect du principe du moindre privilège",
    permissionsIntro = "Notre application ne demande que les autorisations strictement requises techniquement pour établir le tunnel VPN en toute sécurité.",
    vpnKeyPermTitle = "Autorisation VpnService",
    vpnKeyPermStatus = "Autorisation système standard",
    vpnKeyPermDesc = "Gérée automatiquement via la boîte de dialogue de sécurité d'Android lors de la première connexion.",
    notifPermTitle = "Autorisation de notification (Service de premier plan)",
    notifPermGranted = "Accordée et active",
    notifPermRequired = "Requise pour la barre d'état",
    notifPermDesc = "Nécessaire pour afficher une notification permanente indiquant l'état du tunnel et permettant de se déconnecter en un clic.",
    grantPermBtn = "Accorder l'autorisation",
    openSettingsBtn = "Ouvrir les paramètres système",

    onboardingTitle = "Ruvon VPN",
    onboardingSubtitle = "Un VPN rapide, simple et sécurisé pour un Internet plus privé et ouvert à tous.",
    freeFeatureTitle = "Accès 100% gratuit",
    freeFeatureSubtitle = "Aucun paiement requis. Gratuit pour toujours.",
    noRegFeatureTitle = "Sans inscription & Sans journaux",
    noRegFeatureSubtitle = "Commencez instantanément sans email ni compte requis.",
    secureFeatureTitle = "Connexion sécurisée",
    secureFeatureSubtitle = "Protégez votre activité en ligne avec le chiffrement AES-256.",
    onboardingDisclaimer = "En continuant, vous acceptez notre politique de confidentialité et nos règles de sécurité des données.",
    onboardingContinueBtn = "Continuer",

    connectionDetailsTitle = "Détails de la connexion",
    sessionStatsTitle = "Statistiques de la session",
    serverDetailsTitle = "Informations du serveur",
    countryLabel = "Pays",
    uptimeLabel = "Temps de connexion",

    connectedToFormat = "Connecté à %s",
    reconnectingFormat = "Reconnexion au serveur %s…",
    serversRefreshedFormat = "%d serveurs actualisés avec succès !",
    serversRefreshFailed = "Impossible d'actualiser les serveurs en direct. Utilisation des serveurs intégrés rapides.",
    customConfigImported = "Configuration personnalisée ajoutée et activée avec succès.",
    vpnPermissionRequired = "L'autorisation VPN est requise pour se connecter au serveur.",
    logCopiedToClipboard = "Journaux copiés dans le presse-papiers.",

    privacyVerifiedBadgeTitle = "Politique stricte sans journaux (Zero-Logs)",
    privacyVerifiedBadgeSubtitle = "Nous n'enregistrons, ne surveillons et ne partageons aucune activité de navigation ni donnée personnelle.",
    privacySection1Title = "1. Utilisation de VpnService Android et conformité Google Play",
    privacySection1Content = "La fonctionnalité principale de cette application repose exclusivement sur l'API Android VpnService pour créer un tunnel chiffré au niveau de l'appareil. Conformément aux règles du programme pour les développeurs Google Play :\n• VpnService est utilisé strictement pour chiffrer votre connexion Internet et acheminer le trafic via des serveurs OpenVPN sécurisés.\n• Nous n'utilisons jamais VpnService pour rediriger, manipuler ou monétiser le trafic d'autres applications.\n• Aucune publicité n'est injectée dans votre trafic.",
    privacySection2Title = "2. Données jamais collectées (Garantie sans journaux)",
    privacySection2Content = "Notre architecture réseau fonctionne sans aucune conservation de données :\n• Aucun historique de navigation : nous ne voyons ni n'enregistrons les sites ou applications consultés.\n• Aucune requête DNS : les requêtes sont résolues via un DNS privé chiffré avec protection contre les fuites.\n• Aucune adresse IP réelle : votre adresse IP originale et votre position exacte ne sont jamais enregistrées.\n• Aucun contenu de trafic : toutes les données dans le tunnel sont chiffrées de bout en bout.\n• Aucun identifiant personnel : aucune création de compte, e-mail ou téléphone n'est requis.",
    privacySection3Title = "3. Normes de chiffrement et de sécurité technique",
    privacySection3Content = "Tous les tunnels sont sécurisés selon les normes de chiffrement les plus avancées :\n• Protocole OpenVPN avec chiffrement de niveau militaire AES-256-GCM.\n• Négociation cryptographique TLS 1.3 pour l'établissement sécurisé de la session.\n• Kill Switch intégré empêchant toute fuite lors de déconnexions inattendues.\n• Protection contre les fuites DNS via des résolveurs privés chiffrés.",
    privacySection4Title = "4. Métriques de session en temps réel (Mémoire vive uniquement)",
    privacySection4Content = "Les débits de téléchargement et d'envoi en direct ainsi que la durée de session sont calculés uniquement dans la mémoire RAM pendant la connexion active pour l'affichage. Ils ne sont jamais envoyés à des serveurs d'analyse et sont effacés à la déconnexion.",
    privacySection5Title = "5. Aucun partage ni vente de données à des tiers",
    privacySection5Content = "Nous appliquons une politique stricte de ne jamais vendre, louer, céder ou partager les données des utilisateurs avec des annonceurs ou des tiers à des fins commerciales.",
    privacySection6Title = "6. Droits de l'utilisateur et contact",
    privacySection6Content = "Puisque nous ne collectons aucune donnée personnelle, aucun enregistrement identifiable n'existe sur nos serveurs. Vous conservez la liberté totale de vous déconnecter ou de désinstaller l'application à tout moment.\nPour toute question : support@fastvpn.app",
    privacyAcceptButton = "J'ai compris et j'accepte",

    dataSafetySummaryTitle = "Résumé de sécurité des données (Google Play Data Safety)",
    dataCollectionTitle = "Collecte de données",
    dataCollectionValue = "Aucune (0%)",
    dataSharingTitle = "Partage de données",
    dataSharingValue = "Jamais (0%)",
    dataTransitTitle = "Chiffrement en transit",
    dataTransitValue = "Entièrement chiffré",
    dataDeletionTitle = "Suppression de données",
    dataDeletionValue = "Aucune donnée stockée",
    dataCategoriesTitle = "Détail des catégories de données (Google Play)",
    catLocationTitle = "Position géographique précise",
    catLocationStatus = "Jamais accédée ni enregistrée",
    catPersonalTitle = "Infos personnelles (Nom, E-mail, Téléphone)",
    catPersonalStatus = "Non demandées ni collectées",
    catBrowsingTitle = "Historique de navigation et sites Web",
    catBrowsingStatus = "Zéro journal conservé",
    catDeviceTitle = "Identifiants de l'appareil (ID / ID publicitaire)",
    catDeviceStatus = "Jamais lus ni utilisés pour le suivi",
    catThroughputTitle = "Débit du trafic en direct",
    catThroughputStatus = "En mémoire RAM uniquement pendant la connexion",
    dataImpactTitle = "Comment le VPN influence-t-il la consommation de données ?",
    dataImpactContent = "• Le chiffrement OpenVPN ajoute un en-tête de sécurité léger (environ 4 à 7% de surdébit) à chaque paquet, ce qui est la norme pour tous les VPN sécurisés.\n• L'application ne télécharge aucun fichier en arrière-plan à votre insu.\n• Vous pouvez surveiller vos octets émis et reçus en direct depuis le tableau de bord principal.",

    netPermTitle = "Accès Internet et Réseau",
    netPermStatus = "Accordé automatiquement",
    netPermDesc = "Autorisation Android standard pour télécharger la liste des serveurs et acheminer le trafic chiffré.",

    logsDialogTitle = "Journaux en direct d'OpenVPN",
    noLogsAvailable = "Aucun journal de connexion pour le moment…",
    copyButton = "Copier",
    clearButton = "Effacer",

    systemDefaultName = "Par défaut du système",
    systemDefaultSubtitle = "Automatique selon la langue de l'appareil",

    filterFavorites = "Favoris ⭐",
    noFavoritesFound = "Aucun serveur favori pour le moment",
    udpFastLabel = "OpenVPN UDP (Rapide)",
    tcpStableLabel = "OpenVPN TCP (Stable)",
    customConfigImportTitle = "Importer la configuration OpenVPN (.ovpn)",
    customConfigTitle = "Ajouter un serveur personnalisé",
    customConfigNamePlaceholder = "Nom du serveur (ex: Mon serveur privé)",
    customConfigContentPlaceholder = "Collez le contenu du fichier .ovpn ici…",
    saveAndUseBtn = "Enregistrer et utiliser",
    freeGuaranteeBadge = "Cette application est 100% gratuite sans abonnement ni plan payant",
    securityProtocolSettingsTitle = "Paramètres de sécurité et de protocole",
    favoriteServerAction = "Ajouter aux favoris",
    selectedServerAction = "Sélectionné",
    autoServerBadge = "Auto"
)

val SpanishStrings = AppStrings(
    navHome = "Inicio",
    navServers = "Servidores",
    navSettings = "Ajustes",

    appTitle = "Ruvon VPN",
    statusConnected = "Conectado y Seguro",
    statusDisconnected = "Desconectado",
    statusConnecting = "Conectando…",
    statusReconnecting = "Cambiando de servidor…",
    tapToConnect = "Tocar para conectar",
    tapToDisconnect = "Tocar para desconectar",
    tapToCancel = "Cancelar",
    optimalServer = "Servidor más rápido (Auto)",
    optimalServerDesc = "Ubicación óptima según la latencia",
    selectServerTitle = "Seleccionar ubicación",
    download = "Descarga",
    upload = "Subida",
    ping = "Ping",
    duration = "Duración",
    ipAddress = "Dirección IP",
    protocolLabel = "Protocolo",
    connectionProtected = "Tu conexión a Internet está cifrada y segura",
    notProtected = "Actualmente no estás protegido",
    freeAndFastBadge = "Gratis e Ilimitado",

    serversTitle = "Servidores VPN",
    serversSubtitle = "Servidores OpenVPN de alta velocidad en todo el mundo",
    searchPlaceholder = "Buscar país o ciudad…",
    refreshServers = "Actualizar",
    filterAll = "Todos",
    filterFast = "Más rápidos",
    filterLowPing = "Ping bajo",
    noServersFound = "No se encontraron servidores con este criterio",
    serverCountFormat = "%d servidores disponibles (1 por país)",

    settingsTitle = "Ajustes",
    settingsSubtitle = "Seguridad, túneles y preferencias",
    vpnSecurityCategory = "Seguridad y Túnel VPN",
    autoConnectTitle = "Conexión automática",
    autoConnectSubtitle = "Conectar automáticamente al abrir la app",
    killSwitchTitle = "Interruptor de corte (Kill Switch)",
    killSwitchSubtitle = "Bloquear Internet si la conexión VPN se interrumpe",
    dnsLeakTitle = "Protección contra fugas DNS",
    dnsLeakSubtitle = "Forzar consultas DNS privadas y cifradas",
    notificationsTitle = "Notificaciones",
    notificationsSubtitle = "Estado de conexión y desconexión rápida",
    preferencesCategory = "Preferencias e Idioma",
    protocolTitle = "Protocolo",
    languageTitle = "Idioma de la aplicación",
    appearanceTitle = "Apariencia",
    appearanceLight = "Claro",
    appearanceDark = "Oscuro",
    appearanceSystem = "Según el sistema",
    chooseThemeTitle = "Elegir apariencia",
    chooseThemeSubtitle = "Selecciona modo claro, oscuro o del sistema",
    advancedCategory = "Avanzado y Registros",
    connectionLogsTitle = "Registros de conexión",
    viewLiveLogs = "Ver registros de OpenVPN en vivo",
    aboutAppTitle = "Acerca de Fast VPN",
    helpSupportTitle = "Ayuda y Soporte",
    versionFree = "v1.0.0 (100% Gratis)",

    complianceCategory = "Privacidad y Cumplimiento Google Play",
    privacyPolicyTitle = "Política de privacidad",
    privacyPolicySubtitle = "Política estricta sin registros (Zero-Logs)",
    dataSafetyTitle = "Seguridad y Uso de datos",
    dataSafetySubtitle = "Estándares de seguridad de Google Play",
    vpnDisclosureTitle = "Divulgación del servicio VPN",
    vpnDisclosureSubtitle = "Cumplimiento de la política VpnService",
    appPermissionsTitle = "Permisos y Transparencia",
    appPermissionsSubtitle = "Gestión y justificación de permisos",

    chooseLanguageTitle = "Elegir idioma",
    chooseLanguageSubtitle = "Selecciona tu idioma preferido para la app",
    applyLanguageBtn = "Aplicar",
    cancelBtn = "Cancelar",
    closeBtn = "Cerrar",

    disclosureTitle = "Divulgación del servicio VPN y Privacidad",
    disclosureSubtitle = "De acuerdo con las políticas de Google Play para apps VPN, así funciona nuestro servicio para proteger tu privacidad antes de conectarte.",
    disclosurePoint1Title = "Uso esencial de VpnService de Android",
    disclosurePoint1Desc = "La app utiliza la API oficial VpnService de Android exclusivamente para crear un túnel cifrado a nivel de dispositivo.",
    disclosurePoint2Title = "Garantía estricta sin registros (Zero-Logs)",
    disclosurePoint2Desc = "Nunca registramos, monitoreamos ni vendemos tu historial de navegación, consultas DNS, dirección IP real ni datos personales.",
    disclosurePoint3Title = "Estadísticas de sesión efímeras",
    disclosurePoint3Desc = "Las velocidades de subida y bajada se calculan localmente en la memoria RAM solo durante la sesión y se borran al desconectar.",
    agreeAndContinueBtn = "Aceptar y Continuar",
    viewPrivacyPolicyLink = "📜 Política de privacidad",
    viewDataSafetyLink = "🛡️ Seguridad de datos",

    privacyPolicyHeader = "Política de privacidad",
    privacyZeroLogsTitle = "1. Compromiso estricto sin registros (Zero-Logs)",
    privacyZeroLogsDesc = "Mantenemos una política estricta sin registros. NO registramos, guardamos ni monitoreamos: tu IP real, consultas DNS, sitios web visitados ni contenido de tráfico.",
    privacyVpnServiceTitle = "2. Cumplimiento de VpnService en Google Play",
    privacyVpnServiceDesc = "Nuestra app utiliza el servicio oficial VpnService únicamente como túnel cifrado seguro. No inyectamos anuncios ni alteramos tu tráfico.",
    privacySecurityTitle = "3. Estándares de cifrado de alta seguridad",
    privacySecurityDesc = "Todo el tráfico se cifra mediante OpenVPN con cifrado AES-256-GCM, intercambio de claves TLS 1.3 y protección contra fugas DNS.",
    privacyNoSaleTitle = "4. Sin venta ni cesión de datos a terceros",
    privacyNoSaleDesc = "No vendemos, alquilamos ni divulgamos información de usuarios a intermediarios de datos ni empresas publicitarias.",

    dataSafetyHeader = "Seguridad de datos (Data Safety)",
    dataSafetySubheader = "Informe de transparencia alineado con los requisitos de Google Play Console",
    noDataCollected = "No se recopilan datos",
    noDataShared = "No se comparten datos",
    encryptedInTransit = "Cifrado en tránsito",
    overheadNoticeTitle = "Consumo de datos con VPN",
    overheadNoticeDesc = "Debido al encabezado de cifrado y la encapsulación IP, podrías notar un aumento del 5 al 15% en el uso de datos móviles, lo cual es normal en todos los protocolos VPN seguros.",

    permissionsHeader = "Permisos de la aplicación",
    permissionsSubheader = "Cumplimiento del principio de privilegio mínimo",
    permissionsIntro = "Nuestra app solo solicita los permisos técnicos mínimos estrictamente necesarios para ofrecer un túnel VPN seguro.",
    vpnKeyPermTitle = "Permiso VpnService",
    vpnKeyPermStatus = "Permiso estándar del sistema",
    vpnKeyPermDesc = "Se solicita automáticamente mediante el diálogo de seguridad de Android en la primera conexión.",
    notifPermTitle = "Permiso de notificaciones (Servicio en primer plano)",
    notifPermGranted = "Concedido y activo",
    notifPermRequired = "Requerido para la barra de estado",
    notifPermDesc = "Permite mostrar una notificación persistente para monitorear el túnel y desconectarse con un solo toque.",
    grantPermBtn = "Conceder permiso",
    openSettingsBtn = "Abrir ajustes del sistema",

    onboardingTitle = "Ruvon VPN",
    onboardingSubtitle = "Una VPN rápida, sencilla y segura para un Internet más privado y abierto para todos.",
    freeFeatureTitle = "Acceso 100% gratuito",
    freeFeatureSubtitle = "Sin pagos requeridos. Totalmente gratis para siempre.",
    noRegFeatureTitle = "Sin registro y sin registros",
    noRegFeatureSubtitle = "Comienza al instante sin correo electrónico ni cuenta.",
    secureFeatureTitle = "Conexión segura",
    secureFeatureSubtitle = "Protege tu actividad en línea con cifrado AES-256.",
    onboardingDisclaimer = "Al continuar, aceptas nuestra política de privacidad y estándares de seguridad de datos.",
    onboardingContinueBtn = "Continuar",

    connectionDetailsTitle = "Detalles de la conexión",
    sessionStatsTitle = "Estadísticas de la sesión",
    serverDetailsTitle = "Datos del servidor",
    countryLabel = "País",
    uptimeLabel = "Tiempo de actividad",

    connectedToFormat = "Conectado a %s",
    reconnectingFormat = "Reconectando al servidor %s…",
    serversRefreshedFormat = "¡%d servidores actualizados con éxito!",
    serversRefreshFailed = "No se pudieron actualizar los servidores en vivo. Usando servidores integrados rápidos.",
    customConfigImported = "Configuración personalizada agregada y activada con éxito.",
    vpnPermissionRequired = "Se requiere permiso de VPN para conectarse al servidor.",
    logCopiedToClipboard = "Registros copiados al portapapeles.",

    privacyVerifiedBadgeTitle = "Política estricta sin registros (Zero-Logs)",
    privacyVerifiedBadgeSubtitle = "No registramos, rastreamos ni compartimos su actividad de navegación ni datos personales.",
    privacySection1Title = "1. Uso de VpnService de Android y cumplimiento con Google Play",
    privacySection1Content = "La funcionalidad principal de esta aplicación se basa exclusivamente en la API VpnService de Android para crear un túnel cifrado a nivel de dispositivo. De conformidad con las políticas del programa para desarrolladores de Google Play:\n• VpnService se utiliza estrictamente para cifrar su tráfico de Internet y enrutarlo a través de servidores OpenVPN seguros.\n• Nunca usamos VpnService para redirigir, manipular o monetizar el tráfico de otras aplicaciones.\n• No se inyecta publicidad en su tráfico de navegación.",
    privacySection2Title = "2. Información que nunca recopilamos (Garantía sin registros)",
    privacySection2Content = "Nuestra arquitectura de red opera sin retención de datos:\n• Sin historial de navegación: nunca vemos, registramos ni almacenamos los sitios web o aplicaciones que utiliza.\n• Sin consultas DNS: se resuelven mediante DNS privado y cifrado con protección contra fugas.\n• Sin direcciones IP reales: su IP original y su ubicación geográfica exacta nunca se registran.\n• Sin contenido de tráfico: todos los datos en el túnel están cifrados de extremo a extremo.\n• Sin identificadores personales: no se requiere registro de cuenta, correo electrónico ni número de teléfono.",
    privacySection3Title = "3. Estándares de cifrado y seguridad técnica",
    privacySection3Content = "Todos los canales de conexión están protegidos con cifrado líder en la industria:\n• Protocolo OpenVPN con cifrado AES-256-GCM de grado militar.\n• Apretón de manos criptográfico TLS 1.3 para establecimiento de sesión seguro.\n• Kill Switch integrado para evitar fugas de datos ante desconexiones inesperadas.\n• Protección contra fugas DNS mediante solucionadores privados cifrados.",
    privacySection4Title = "4. Métricas de sesión en tiempo real (Solo en memoria RAM)",
    privacySection4Content = "Los contadores de velocidad de descarga y subida y la duración de la sesión se calculan exclusivamente en la memoria volátil (RAM) del dispositivo durante la conexión activa para mostrar el panel. Nunca se transmiten a servidores de análisis y se eliminan por completo al desconectar.",
    privacySection5Title = "5. Sin venta ni cesión de datos a terceros",
    privacySection5Content = "Mantenemos una política estricta de nunca vender, alquilar, licenciar o divulgar datos de usuarios a anunciantes, intermediarios de datos ni a terceros bajo ningún concepto.",
    privacySection6Title = "6. Derechos del usuario y contacto",
    privacySection6Content = "Dado que no recopilamos datos personales, no hay registros persistentes e identificables en nuestros servidores. Tiene el control total para desconectar o desinstalar la aplicación en cualquier momento.\nPara consultas técnicas: support@fastvpn.app",
    privacyAcceptButton = "Entendido y de acuerdo",

    dataSafetySummaryTitle = "Resumen de seguridad de datos (Google Play Data Safety)",
    dataCollectionTitle = "Recopilación de datos",
    dataCollectionValue = "Ninguna (0%)",
    dataSharingTitle = "Datos compartidos",
    dataSharingValue = "Nunca (0%)",
    dataTransitTitle = "Cifrado en tránsito",
    dataTransitValue = "Totalmente cifrado",
    dataDeletionTitle = "Eliminación de datos",
    dataDeletionValue = "Sin datos almacenados",
    dataCategoriesTitle = "Detalle de categorías de datos (Google Play)",
    catLocationTitle = "Ubicación geográfica precisa",
    catLocationStatus = "Nunca se accede ni se registra",
    catPersonalTitle = "Información personal (Nombre, Email, Teléfono)",
    catPersonalStatus = "No solicitada ni recopilada",
    catBrowsingTitle = "Historial de navegación y sitios web",
    catBrowsingStatus = "Cero registros guardados",
    catDeviceTitle = "Identificadores de dispositivo (ID / ID de publicidad)",
    catDeviceStatus = "Nunca se leen ni se usan para rastreo",
    catThroughputTitle = "Rendimiento del tráfico en vivo",
    catThroughputStatus = "Solo en memoria RAM durante la conexión",
    dataImpactTitle = "¿Cómo afecta la VPN al consumo de datos?",
    dataImpactContent = "• El cifrado OpenVPN agrega un encabezado de seguridad adicional (aprox. 4–7% de sobrecarga) a cada paquete, lo cual es estándar en todas las VPN seguras.\n• La aplicación nunca descarga archivos en segundo plano sin su conocimiento.\n• Puede supervisar los bytes enviados y recibidos en tiempo real directamente en el panel principal.",

    netPermTitle = "Acceso a Internet y Red",
    netPermStatus = "Otorgado automáticamente",
    netPermDesc = "Permiso estándar de Android para descargar la lista de servidores y transmitir tráfico cifrado.",

    logsDialogTitle = "Registros en vivo de OpenVPN",
    noLogsAvailable = "Aún no hay registros de conexión…",
    copyButton = "Copiar",
    clearButton = "Borrar",

    systemDefaultName = "Predeterminado del sistema",
    systemDefaultSubtitle = "Automático según el idioma del dispositivo",

    filterFavorites = "Favoritos ⭐",
    noFavoritesFound = "No hay servidores favoritos aún",
    udpFastLabel = "OpenVPN UDP (Más rápido)",
    tcpStableLabel = "OpenVPN TCP (Más estable)",
    customConfigImportTitle = "Importar configuración OpenVPN (.ovpn)",
    customConfigTitle = "Añadir servidor personalizado",
    customConfigNamePlaceholder = "Nombre del servidor (ej: Mi servidor privado)",
    customConfigContentPlaceholder = "Pegue el contenido del archivo .ovpn aquí…",
    saveAndUseBtn = "Guardar y usar",
    freeGuaranteeBadge = "Esta aplicación es 100% gratuita sin suscripciones ni planes de pago",
    securityProtocolSettingsTitle = "Configuración de seguridad y protocolo",
    favoriteServerAction = "Añadir a favoritos",
    selectedServerAction = "Seleccionado",
    autoServerBadge = "Auto"
)


val GermanStrings = AppStrings(
    navHome = "Startseite",
    navServers = "Server",
    navSettings = "Einstellungen",
    appTitle = "Ruvon VPN",
    statusConnected = "Verbunden & Geschützt",
    statusDisconnected = "Getrennt",
    statusConnecting = "Verbindung wird hergestellt…",
    statusReconnecting = "Server wird gewechselt…",
    tapToConnect = "Zum Verbinden tippen",
    tapToDisconnect = "Zum Trennen tippen",
    tapToCancel = "Abbrechen",
    optimalServer = "Schnellster Server (Auto)",
    optimalServerDesc = "Optimaler Standort basierend auf Latenz",
    selectServerTitle = "Standort wählen",
    download = "Download",
    upload = "Upload",
    ping = "Ping",
    duration = "Dauer",
    ipAddress = "IP-Adresse",
    protocolLabel = "Protokoll",
    connectionProtected = "Ihre Internetverbindung ist verschlüsselt",
    notProtected = "Sie sind derzeit ungeschützt",
    freeAndFastBadge = "Kostenlos & Unbegrenzt",
    serversTitle = "VPN-Server",
    serversSubtitle = "Weltweite Hochgeschwindigkeits-OpenVPN-Server",
    searchPlaceholder = "Nach Land oder Stadt suchen…",
    refreshServers = "Aktualisieren",
    filterAll = "Alle",
    filterFast = "Schnellste",
    filterLowPing = "Niedriger Ping",
    noServersFound = "Keine Server gefunden",
    serverCountFormat = "%d Server verfügbar",
    settingsTitle = "Einstellungen",
    settingsSubtitle = "Sicherheit, Tunneling & Präferenzen",
    vpnSecurityCategory = "VPN-Sicherheit & Tunneling",
    autoConnectTitle = "Automatisch verbinden",
    autoConnectSubtitle = "Beim Starten der App automatisch verbinden",
    killSwitchTitle = "Kill Switch",
    killSwitchSubtitle = "Internet sperren, falls VPN abbricht",
    dnsLeakTitle = "DNS-Leak-Schutz",
    dnsLeakSubtitle = "Private verschlüsselte DNS-Server erzwingen",
    notificationsTitle = "Benachrichtigungen",
    notificationsSubtitle = "Verbindungsstatus & Schnellaktionen",
    preferencesCategory = "Präferenzen",
    protocolTitle = "Protokoll",
    languageTitle = "Sprache",
    appearanceTitle = "Erscheinungsbild",
    appearanceLight = "Hell",
    appearanceDark = "Dunkel",
    appearanceSystem = "Systemstandard",
    chooseThemeTitle = "Erscheinungsbild wählen",
    chooseThemeSubtitle = "Helles, dunkles oder System-Design auswählen",
    advancedCategory = "Erweitert",
    connectionLogsTitle = "Verbindungsprotokolle",
    viewLiveLogs = "Live-Protokolle anzeigen",
    aboutAppTitle = "Über Ruvon VPN",
    helpSupportTitle = "Hilfe & Support",
    versionFree = "Kostenlose Version",
    complianceCategory = "Rechtliches & Datenschutz",
    privacyPolicyTitle = "Datenschutzerklärung",
    privacyPolicySubtitle = "Unsere strikte No-Logs-Garantie",
    dataSafetyTitle = "Datensicherheit",
    dataSafetySubtitle = "Google Play Datensicherheitserklärung",
    vpnDisclosureTitle = "VPN-Dienst-Transparenz",
    vpnDisclosureSubtitle = "Informationen zur Nutzung von VpnService",
    appPermissionsTitle = "App-Berechtigungen",
    appPermissionsSubtitle = "Transparenz über alle Berechtigungen",
    chooseLanguageTitle = "Sprache wählen",
    chooseLanguageSubtitle = "Wählen Sie Ihre bevorzugte Sprache",
    applyLanguageBtn = "Anwenden",
    cancelBtn = "Abbrechen",
    closeBtn = "Schließen",
    disclosureTitle = "VPN-Dienst-Transparenz",
    disclosureSubtitle = "Wichtige Information vor der Verbindung",
    disclosurePoint1Title = "Verschlüsselter Tunnel",
    disclosurePoint1Desc = "Ruvon VPN nutzt den Android VpnService, um den Datenverkehr auf Geräteebene zu verschlüsseln.",
    disclosurePoint2Title = "Strikte No-Logs-Richtlinie",
    disclosurePoint2Desc = "Wir protokollieren, speichern oder verfolgen niemals Ihre Surfaktivitäten oder IP-Adressen.",
    disclosurePoint3Title = "100% Kostenlos",
    disclosurePoint3Desc = "Keine versteckten Gebühren, keine Konten und keine Abonnements erforderlich.",
    agreeAndContinueBtn = "Zustimmen & Fortfahren",
    viewPrivacyPolicyLink = "Datenschutzerklärung lesen",
    viewDataSafetyLink = "Datensicherheit einsehen",
    privacyPolicyHeader = "Datenschutzerklärung",
    privacyZeroLogsTitle = "100% No-Logs-Garantie",
    privacyZeroLogsDesc = "Wir erfassen oder speichern zu keinem Zeitpunkt IP-Adressen, Surfverläufe, DNS-Abfragen oder Datenverkehr.",
    privacyVpnServiceTitle = "Verwendung des VpnService",
    privacyVpnServiceDesc = "Der Android VpnService wird ausschließlich zur sicheren Verschlüsselung des Tunnels verwendet.",
    privacySecurityTitle = "Verschlüsselungsstandards",
    privacySecurityDesc = "Modernste Verschlüsselung mit OpenVPN und AES-256-GCM schützt Ihre Privatsphäre.",
    privacyNoSaleTitle = "Kein Datenverkauf",
    privacyNoSaleDesc = "Wir verkaufen, vermieten oder teilen niemals Benutzerdaten mit Dritten oder Werbetreibenden.",
    dataSafetyHeader = "Datensicherheit & Transparenz",
    dataSafetySubheader = "Google Play Datensicherheits-Standard",
    noDataCollected = "Keine Datenerfassung",
    noDataShared = "Keine Datenweitergabe",
    encryptedInTransit = "Vollständig verschlüsselt",
    overheadNoticeTitle = "Netzwerk-Overhead",
    overheadNoticeDesc = "VPN-Verschlüsselung benötigt ca. 4-7% zusätzliche Daten für Sicherheitsheader.",
    permissionsHeader = "App-Berechtigungen",
    permissionsSubheader = "Volle Transparenz",
    permissionsIntro = "Ruvon VPN benötigt nur minimale Berechtigungen für den Betrieb.",
    vpnKeyPermTitle = "VPN-Verbindungsberechtigung",
    vpnKeyPermStatus = "Erforderlich",
    vpnKeyPermDesc = "Ermöglicht Android das Einrichten des sicheren VPN-Tunnels.",
    notifPermTitle = "Benachrichtigungen",
    notifPermGranted = "Erteilt",
    notifPermRequired = "Nicht erforderlich",
    notifPermDesc = "Benachrichtigungen für Verbindungsstatus.",
    grantPermBtn = "Erteilen",
    openSettingsBtn = "Einstellungen öffnen",
    onboardingTitle = "Willkommen bei Ruvon VPN",
    onboardingSubtitle = "Sicher, schnell und unbegrenzt",
    freeFeatureTitle = "Kostenlos & Unbegrenzt",
    freeFeatureSubtitle = "Keine Bandbreiten- oder Zeitbeschränkungen",
    noRegFeatureTitle = "Keine Registrierung",
    noRegFeatureSubtitle = "Sofort verbinden ohne Konto",
    secureFeatureTitle = "Vollständig verschlüsselt",
    secureFeatureSubtitle = "AES-256-GCM militärische Sicherheit",
    onboardingDisclaimer = "Durch Fortfahren stimmen Sie unserer Datenschutzerklärung zu.",
    onboardingContinueBtn = "Jetzt starten",
    connectionDetailsTitle = "Verbindungsdetails",
    sessionStatsTitle = "Sitzungsstatistiken",
    serverDetailsTitle = "Serverdetails",
    countryLabel = "Standort",
    uptimeLabel = "Laufzeit",
    connectedToFormat = "Verbunden mit %s",
    reconnectingFormat = "Verbinde mit %s…",
    serversRefreshedFormat = "%d Server aktualisiert",
    serversRefreshFailed = "Aktualisierung fehlgeschlagen. Bitte Verbindung prüfen.",
    customConfigImported = "Serverkonfiguration erfolgreich importiert!",
    vpnPermissionRequired = "VPN-Berechtigung ist erforderlich.",
    logCopiedToClipboard = "Protokolle in Zwischenablage kopiert",
    privacyVerifiedBadgeTitle = "Geprüfte No-Logs-Richtlinie",
    privacyVerifiedBadgeSubtitle = "Null Datenerfassung garantiert",
    privacySection1Title = "1. Keine Protokollierung",
    privacySection1Content = "Wir speichern zu keinem Zeitpunkt Protokolle über Ihre Online-Aktivitäten.",
    privacySection2Title = "2. OpenVPN-Tunneling",
    privacySection2Content = "Sämtlicher Datenverkehr wird über sichere OpenVPN-Tunnel geleitet.",
    privacySection3Title = "3. AES-256-GCM Verschlüsselung",
    privacySection3Content = "Verschlüsselung nach Militärstandard schützt Ihre Daten vor Abhören.",
    privacySection4Title = "4. Sitzungsdaten nur im RAM",
    privacySection4Content = "Verbindungsdaten werden nur temporär im Arbeitsspeicher gehalten und beim Trennen sofort gelöscht.",
    privacySection5Title = "5. Kein Datenverkauf",
    privacySection5Content = "Ihre Daten werden unter keinen Umständen an Dritte weitergegeben.",
    privacySection6Title = "6. Kontakt",
    privacySection6Content = "Bei Fragen erreichen Sie uns unter: support@fastvpn.app",
    privacyAcceptButton = "Verstanden & Akzeptiert",
    dataSafetySummaryTitle = "Datensicherheitsübersicht",
    dataCollectionTitle = "Datenerfassung",
    dataCollectionValue = "Keine (0%)",
    dataSharingTitle = "Datenweitergabe",
    dataSharingValue = "Niemals (0%)",
    dataTransitTitle = "Verschlüsselung bei Übertragung",
    dataTransitValue = "Vollständig verschlüsselt",
    dataDeletionTitle = "Datenlöschung",
    dataDeletionValue = "Keine Daten gespeichert",
    dataCategoriesTitle = "Datenkategorien",
    catLocationTitle = "Genauer Standort",
    catLocationStatus = "Wird niemals erfasst",
    catPersonalTitle = "Persönliche Daten",
    catPersonalStatus = "Nicht erfasst",
    catBrowsingTitle = "Browserverlauf",
    catBrowsingStatus = "Null Protokolle",
    catDeviceTitle = "Gerätekennungen",
    catDeviceStatus = "Werden nicht erfasst",
    catThroughputTitle = "Echtzeit-Durchsatz",
    catThroughputStatus = "Nur im flüchtigen Speicher",
    dataImpactTitle = "VPN-Datenverbrauch",
    dataImpactContent = "Die OpenVPN-Verschlüsselung benötigt ca. 4-7% Overhead für Sicherheitsheader. Es werden keine Hintergrunddaten ohne Ihr Wissen geladen.",
    netPermTitle = "Netzwerkzugriff",
    netPermStatus = "Automatisch erteilt",
    netPermDesc = "Erforderlich zum Herunterladen der Serverliste und Übertragen des Tunnels.",
    logsDialogTitle = "OpenVPN Live-Protokolle",
    noLogsAvailable = "Noch keine Protokolle vorhanden…",
    copyButton = "Kopieren",
    clearButton = "Löschen",
    systemDefaultName = "Systemstandard",
    systemDefaultSubtitle = "Automatisch nach Gerätesprache",
    filterFavorites = "Favoriten ⭐",
    noFavoritesFound = "Noch keine Favoriten vorhanden",
    udpFastLabel = "OpenVPN UDP (Schneller)",
    tcpStableLabel = "OpenVPN TCP (Stabiler)",
    customConfigImportTitle = "OpenVPN-Konfiguration (.ovpn) importieren",
    customConfigTitle = "Benutzerdefinierten Server hinzufügen",
    customConfigNamePlaceholder = "Servername",
    customConfigContentPlaceholder = ".ovpn-Inhalt hier einfügen…",
    saveAndUseBtn = "Speichern & Verwenden",
    freeGuaranteeBadge = "100% kostenlos ohne Abonnements",
    securityProtocolSettingsTitle = "Sicherheit & Protokoll",
    favoriteServerAction = "Zu Favoriten hinzufügen",
    selectedServerAction = "Ausgewählt",
    autoServerBadge = "Auto"
)

val RussianStrings = AppStrings(
    navHome = "Главная",
    navServers = "Серверы",
    navSettings = "Настройки",
    appTitle = "Ruvon VPN",
    statusConnected = "Подключено и защищено",
    statusDisconnected = "Отключено",
    statusConnecting = "Подключение…",
    statusReconnecting = "Смена сервера…",
    tapToConnect = "Нажмите для подключения",
    tapToDisconnect = "Нажмите для отключения",
    tapToCancel = "Отмена",
    optimalServer = "Самый быстрый сервер (Авто)",
    optimalServerDesc = "Оптимальное местоположение по задержке",
    selectServerTitle = "Выбрать сервер",
    download = "Загрузка",
    upload = "Отдача",
    ping = "Пинг",
    duration = "Время",
    ipAddress = "IP-адрес",
    protocolLabel = "Протокол",
    connectionProtected = "Интернет-соединение надежно зашифровано",
    notProtected = "В настоящее время соединение не защищено",
    freeAndFastBadge = "Бесплатно и без ограничений",
    serversTitle = "VPN Серверы",
    serversSubtitle = "Глобальные скоростные серверы OpenVPN",
    searchPlaceholder = "Поиск по стране или городу…",
    refreshServers = "Обновить",
    filterAll = "Все",
    filterFast = "Быстрые",
    filterLowPing = "Низкий пинг",
    noServersFound = "Серверы не найдены",
    serverCountFormat = "Доступно серверов: %d",
    settingsTitle = "Настройки",
    settingsSubtitle = "Безопасность, туннель и параметры",
    vpnSecurityCategory = "Безопасность и туннелирование",
    autoConnectTitle = "Автоподключение",
    autoConnectSubtitle = "Подключаться автоматически при запуске",
    killSwitchTitle = "Kill Switch",
    killSwitchSubtitle = "Блокировать интернет при обрыве VPN",
    dnsLeakTitle = "Защита от утечек DNS",
    dnsLeakSubtitle = "Принудительные зашифрованные DNS-запросы",
    notificationsTitle = "Уведомления",
    notificationsSubtitle = "Статус подключения и быстрое отключение",
    preferencesCategory = "Параметры",
    protocolTitle = "Протокол",
    languageTitle = "Язык",
    appearanceTitle = "Оформление",
    appearanceLight = "Светлая",
    appearanceDark = "Тёмная",
    appearanceSystem = "Как в системе",
    chooseThemeTitle = "Выбор темы",
    chooseThemeSubtitle = "Выберите светлую, тёмную или системную тему",
    advancedCategory = "Дополнительно",
    connectionLogsTitle = "Журнал подключения",
    viewLiveLogs = "Просмотр логов в реальном времени",
    aboutAppTitle = "О приложении Ruvon VPN",
    helpSupportTitle = "Помощь и поддержка",
    versionFree = "Бесплатная версия",
    complianceCategory = "Конфиденциальность и безопасность",
    privacyPolicyTitle = "Политика конфиденциальности",
    privacyPolicySubtitle = "Строгая политика отсутствия логов (No-Logs)",
    dataSafetyTitle = "Безопасность данных",
    dataSafetySubtitle = "Декларация безопасности Google Play",
    vpnDisclosureTitle = "Использование службы VPN",
    vpnDisclosureSubtitle = "Сведения об использовании VpnService",
    appPermissionsTitle = "Разрешения приложения",
    appPermissionsSubtitle = "Прозрачность системных разрешений",
    chooseLanguageTitle = "Выбор языка",
    chooseLanguageSubtitle = "Выберите предпочтительный язык интерфейса",
    applyLanguageBtn = "Применить",
    cancelBtn = "Отмена",
    closeBtn = "Закрыть",
    disclosureTitle = "Информация о службе VPN",
    disclosureSubtitle = "Важное уведомление перед подключением",
    disclosurePoint1Title = "Зашифрованный туннель",
    disclosurePoint1Desc = "Ruvon VPN использует Android VpnService для надежного шифрования сетевого трафика.",
    disclosurePoint2Title = "Строгий отказ от ведения логов",
    disclosurePoint2Desc = "Мы никогда не отслеживаем, не сохраняем и не анализируем ваши посещенные сайты или IP.",
    disclosurePoint3Title = "100% Бесплатно",
    disclosurePoint3Desc = "Без подписок, платежей и обязательной регистрации.",
    agreeAndContinueBtn = "Принять и продолжить",
    viewPrivacyPolicyLink = "Политика конфиденциальности",
    viewDataSafetyLink = "Безопасность данных",
    privacyPolicyHeader = "Политика конфиденциальности",
    privacyZeroLogsTitle = "Гарантия нулевых логов (Zero Logs)",
    privacyZeroLogsDesc = "Мы не собираем историю просмотров, IP-адреса, запросы DNS или содержимое трафика.",
    privacyVpnServiceTitle = "Использование VpnService",
    privacyVpnServiceDesc = "VpnService используется исключительно для маршрутизации трафика через безопасный туннель.",
    privacySecurityTitle = "Стандарты безопасности",
    privacySecurityDesc = "Военное шифрование OpenVPN и AES-256-GCM защищает ваши данные от перехвата.",
    privacyNoSaleTitle = "Никакой продажи данных",
    privacyNoSaleDesc = "Мы никогда не продаем и не передаем пользовательские данные третьим лицам или рекламодателям.",
    dataSafetyHeader = "Безопасность данных",
    dataSafetySubheader = "Стандарт безопасности Google Play",
    noDataCollected = "Данные не собираются",
    noDataShared = "Данные не передаются",
    encryptedInTransit = "Полностью зашифровано",
    overheadNoticeTitle = "Сетевой оверхед",
    overheadNoticeDesc = "Шифрование добавляет около 4-7% служебных данных к общему трафику.",
    permissionsHeader = "Разрешения приложения",
    permissionsSubheader = "Полная прозрачность",
    permissionsIntro = "Ruvon VPN требует только минимально необходимые разрешения.",
    vpnKeyPermTitle = "Разрешение на создание VPN",
    vpnKeyPermStatus = "Обязательно",
    vpnKeyPermDesc = "Необходимо системе Android для установления защищенного туннеля.",
    notifPermTitle = "Уведомления",
    notifPermGranted = "Предоставлено",
    notifPermRequired = "Не требуется",
    notifPermDesc = "Отображение статуса соединения.",
    grantPermBtn = "Предоставить",
    openSettingsBtn = "Открыть настройки",
    onboardingTitle = "Добро пожаловать в Ruvon VPN",
    onboardingSubtitle = "Быстро, безопасно и без ограничений",
    freeFeatureTitle = "Бесплатно и безлимитно",
    freeFeatureSubtitle = "Без ограничений скорости и объема трафика",
    noRegFeatureTitle = "Без регистрации",
    noRegFeatureSubtitle = "Подключение в один клик без учетных записей",
    secureFeatureTitle = "Надежное шифрование",
    secureFeatureSubtitle = "Защита военного уровня AES-256-GCM",
    onboardingDisclaimer = "Продолжая, вы соглашаетесь с условиями политики конфиденциальности.",
    onboardingContinueBtn = "Начать использование",
    connectionDetailsTitle = "Сведения о подключении",
    sessionStatsTitle = "Статистика сессии",
    serverDetailsTitle = "Параметры сервера",
    countryLabel = "Страна",
    uptimeLabel = "Время работы",
    connectedToFormat = "Подключено к %s",
    reconnectingFormat = "Подключение к %s…",
    serversRefreshedFormat = "Обновлено серверов: %d",
    serversRefreshFailed = "Не удалось обновить серверы. Проверьте интернет.",
    customConfigImported = "Конфигурация сервера успешно импортирована!",
    vpnPermissionRequired = "Требуется разрешение на подключение VPN.",
    logCopiedToClipboard = "Журнал скопирован в буфер обмена",
    privacyVerifiedBadgeTitle = "Проверенная политика No-Logs",
    privacyVerifiedBadgeSubtitle = "Гарантированное отсутствие сбора данных",
    privacySection1Title = "1. Нулевое ведение логов",
    privacySection1Content = "Мы не сохраняем никаких журналов активности пользователей в сети.",
    privacySection2Title = "2. Туннелирование OpenVPN",
    privacySection2Content = "Весь сетевой трафик проходит через изолированные зашифрованные туннели.",
    privacySection3Title = "3. Шифрование AES-256-GCM",
    privacySection3Content = "Шифрование военного уровня надежно защищает передаваемые данные.",
    privacySection4Title = "4. Данные только в оперативной памяти (RAM)",
    privacySection4Content = "Счетчики трафика хранятся исключительно в оперативной памяти и удаляются при отключении.",
    privacySection5Title = "5. Никакой продажи данных",
    privacySection5Content = "Пользовательские данные ни при каких обстоятельствах не передаются третьим лицам.",
    privacySection6Title = "6. Контакты",
    privacySection6Content = "По вопросам поддержки: support@fastvpn.app",
    privacyAcceptButton = "Понятно и согласен",
    dataSafetySummaryTitle = "Сводка безопасности данных",
    dataCollectionTitle = "Сбор данных",
    dataCollectionValue = "Отсутствует (0%)",
    dataSharingTitle = "Передача данных",
    dataSharingValue = "Никогда (0%)",
    dataTransitTitle = "Шифрование при передаче",
    dataTransitValue = "Полностью зашифровано",
    dataDeletionTitle = "Удаление данных",
    dataDeletionValue = "Данные не сохраняются",
    dataCategoriesTitle = "Категории данных",
    catLocationTitle = "Точное местоположение",
    catLocationStatus = "Никогда не собирается",
    catPersonalTitle = "Персональные данные",
    catPersonalStatus = "Не запрашиваются",
    catBrowsingTitle = "История просмотров",
    catBrowsingStatus = "Ноль записей",
    catDeviceTitle = "Идентификаторы устройства",
    catDeviceStatus = "Не считываются",
    catThroughputTitle = "Текущий трафик",
    catThroughputStatus = "Только в оперативной памяти",
    dataImpactTitle = "Расход трафика через VPN",
    dataImpactContent = "Шифрование OpenVPN добавляет около 4-7% служебных данных к пакетам. Приложение не производит скрытых фоновых загрузок.",
    netPermTitle = "Доступ к сети",
    netPermStatus = "Предоставлено автоматически",
    netPermDesc = "Необходимо для загрузки списка серверов и передачи трафика.",
    logsDialogTitle = "Логи OpenVPN",
    noLogsAvailable = "Логи пока отсутствуют…",
    copyButton = "Копировать",
    clearButton = "Очистить",
    systemDefaultName = "Системный по умолчанию",
    systemDefaultSubtitle = "Автоматически по языку устройства",
    filterFavorites = "Избранное ⭐",
    noFavoritesFound = "В избранном пока ничего нет",
    udpFastLabel = "OpenVPN UDP (Быстрее)",
    tcpStableLabel = "OpenVPN TCP (Стабильнее)",
    customConfigImportTitle = "Импорт файла .ovpn",
    customConfigTitle = "Добавить свой сервер",
    customConfigNamePlaceholder = "Имя сервера",
    customConfigContentPlaceholder = "Вставьте содержимое файла .ovpn сюда…",
    saveAndUseBtn = "Сохранить и использовать",
    freeGuaranteeBadge = "100% бесплатно без подписок",
    securityProtocolSettingsTitle = "Безопасность и протокол",
    favoriteServerAction = "В избранное",
    selectedServerAction = "Выбрано",
    autoServerBadge = "Авто"
)

val PersianStrings = AppStrings(
    navHome = "خانه",
    navServers = "سرورها",
    navSettings = "تنظیمات",
    appTitle = "Ruvon VPN",
    statusConnected = "متصل و ایمن شد",
    statusDisconnected = "قطع شد",
    statusConnecting = "در حال اتصال…",
    statusReconnecting = "تغییر سرور…",
    tapToConnect = "برای اتصال ضربه بزنید",
    tapToDisconnect = "برای قطع اتصال ضربه بزنید",
    tapToCancel = "لغو",
    optimalServer = "سریع‌ترین سرور (خودکار)",
    optimalServerDesc = "بهترین موقعیت بر اساس کمترین پینگ",
    selectServerTitle = "انتخاب سرور",
    download = "دانلود",
    upload = "آپلود",
    ping = "پینگ",
    duration = "مدت زمان",
    ipAddress = "آدرس IP",
    protocolLabel = "پروتکل",
    connectionProtected = "اتصال اینترنت شما رمزگذاری شده است",
    notProtected = "شما در حال حاضر محافظت نشده‌اید",
    freeAndFastBadge = "رایگان و نامحدود",
    serversTitle = "سرورهای VPN",
    serversSubtitle = "سرورهای پرسرعت OpenVPN در سراسر جهان",
    searchPlaceholder = "جستجو بر اساس کشور یا شهر…",
    refreshServers = "تازه‌سازی",
    filterAll = "همه",
    filterFast = "سریع‌ترین",
    filterLowPing = "پینگ پایین",
    noServersFound = "هیچ سروری یافت نشد",
    serverCountFormat = "%d سرور موجود است",
    settingsTitle = "تنظیمات",
    settingsSubtitle = "امنیت، تونل و اولویت‌ها",
    vpnSecurityCategory = "امنیت VPN و تونل‌سازی",
    autoConnectTitle = "اتصال خودکار",
    autoConnectSubtitle = "اتصال خودکار هنگام باز شدن برنامه",
    killSwitchTitle = "سوئیچ قطع اضطراری (Kill Switch)",
    killSwitchSubtitle = "مسدود کردن اینترنت در صورت قطع اتصال VPN",
    dnsLeakTitle = "محافظت در برابر نشت DNS",
    dnsLeakSubtitle = "اجبار به استفاده از DNS خصوصی رمزگذاری‌شده",
    notificationsTitle = "اعلان‌ها",
    notificationsSubtitle = "وضعیت اتصال و قطع سریع",
    preferencesCategory = "اولویت‌ها",
    protocolTitle = "پروتکل",
    languageTitle = "زبان",
    appearanceTitle = "ظاهر برنامه",
    appearanceLight = "روشن",
    appearanceDark = "تاریک",
    appearanceSystem = "هماهنگ با سیستم",
    chooseThemeTitle = "انتخاب تم",
    chooseThemeSubtitle = "انتخاب حالت روشن، تاریک یا پیش‌فرض سیستم",
    advancedCategory = "پیشرفته",
    connectionLogsTitle = "گزارش‌های اتصال",
    viewLiveLogs = "مشاهده گزارش‌های زنده",
    aboutAppTitle = "درباره Ruvon VPN",
    helpSupportTitle = "راهنما و پشتیبانی",
    versionFree = "نسخه رایگان",
    complianceCategory = "حفظ حریم خصوصی و امنیت",
    privacyPolicyTitle = "سیاست حفظ حریم خصوصی",
    privacyPolicySubtitle = "تضمین قطعی عدم ذخیره لاگ (No-Logs)",
    dataSafetyTitle = "امنیت داده‌ها",
    dataSafetySubtitle = "بیانیه امنیت داده‌های Google Play",
    vpnDisclosureTitle = "شفافیت سرویس VPN",
    vpnDisclosureSubtitle = "اطلاعات مربوط به استفاده از VpnService",
    appPermissionsTitle = "مجوزهای برنامه",
    appPermissionsSubtitle = "شفافیت مجوزهای دسترسی",
    chooseLanguageTitle = "انتخاب زبان",
    chooseLanguageSubtitle = "زبان مورد نظر خود را انتخاب کنید",
    applyLanguageBtn = "اعمال",
    cancelBtn = "انصراف",
    closeBtn = "بستن",
    disclosureTitle = "شفافیت سرویس VPN",
    disclosureSubtitle = "اطلاعیه مهم پیش از برقراری اتصال",
    disclosurePoint1Title = "تونل رمزگذاری‌شده",
    disclosurePoint1Desc = "این برنامه از Android VpnService برای رمزگذاری ترافیک دستگاه شما استفاده می‌کند.",
    disclosurePoint2Title = "سیاست قطعی عدم ذخیره گزارش",
    disclosurePoint2Desc = "ما هرگز سابقه مرور، آدرس IP یا فعالیت‌های شما را ضبط نمی‌کنیم.",
    disclosurePoint3Title = "۱۰۰٪ رایگان",
    disclosurePoint3Desc = "بدون نیاز به اشتراک، پرداخت هزینه یا ساخت حساب کاربری.",
    agreeAndContinueBtn = "موافقت و ادامه",
    viewPrivacyPolicyLink = "مشاهده سیاست حریم خصوصی",
    viewDataSafetyLink = "مشاهده امنیت داده‌ها",
    privacyPolicyHeader = "سیاست حفظ حریم خصوصی",
    privacyZeroLogsTitle = "تضمین عدم ذخیره لاگ (Zero-Logs)",
    privacyZeroLogsDesc = "هیچ گزارش فعالیتی از شما در سرورهای ما ذخیره نمی‌شود.",
    privacyVpnServiceTitle = "استفاده از سرویس VpnService",
    privacyVpnServiceDesc = "سرویس VpnService فقط برای هدایت امن ترافیک استفاده می‌شود.",
    privacySecurityTitle = "استانداردهای امنیتی",
    privacySecurityDesc = "رمزگذاری فوق‌العاده قوی AES-256-GCM برای محافظت از حریم خصوصی شما.",
    privacyNoSaleTitle = "عدم فروش اطلاعات",
    privacyNoSaleDesc = "اطلاعات کاربران هرگز به اشخاص ثالث یا تبلیغ‌کنندگان فروخته نخواهد شد.",
    dataSafetyHeader = "امنیت داده‌ها و شفافیت",
    dataSafetySubheader = "استاندارد ایمنی داده‌های Google Play",
    noDataCollected = "عدم جمع‌آوری داده",
    noDataShared = "عدم اشتراک‌گذاری داده",
    encryptedInTransit = "کاملاً رمزگذاری‌شده در انتقال",
    overheadNoticeTitle = "مصرف داده در رمزگذاری",
    overheadNoticeDesc = "رمزگذاری حدود ۴ تا ۷ درصد به حجم بسته‌ها اضافه می‌کند.",
    permissionsHeader = "مجوزهای برنامه",
    permissionsSubheader = "شفافیت کامل",
    permissionsIntro = "برنامه فقط به حداقل مجوزهای ضروری نیاز دارد.",
    vpnKeyPermTitle = "مجوز ایجاد اتصال VPN",
    vpnKeyPermStatus = "الزامی",
    vpnKeyPermDesc = "برای ساخت تونل امن اندروید ضروری است.",
    notifPermTitle = "اعلان‌ها",
    notifPermGranted = "داده شده",
    notifPermRequired = "اختیاری",
    notifPermDesc = "نمایش وضعیت اتصال.",
    grantPermBtn = "اعطا",
    openSettingsBtn = "باز کردن تنظیمات",
    onboardingTitle = "به Ruvon VPN خوش آمدید",
    onboardingSubtitle = "سریع، امن و کاملاً نامحدود",
    freeFeatureTitle = "رایگان و بدون محدودیت",
    freeFeatureSubtitle = "بدون محدودیت حجم و زمان",
    noRegFeatureTitle = "بدون ثبت‌نام",
    noRegFeatureSubtitle = "اتصال با یک لمس بدون نیاز به ثبت حساب",
    secureFeatureTitle = "رمزگذاری پیشرفته",
    secureFeatureSubtitle = "امنیت در سطح نظامی AES-256-GCM",
    onboardingDisclaimer = "با ادامه، با سیاست حفظ حریم خصوصی موافقت می‌کنید.",
    onboardingContinueBtn = "شروع کنید",
    connectionDetailsTitle = "جزئیات اتصال",
    sessionStatsTitle = "آمار نشست",
    serverDetailsTitle = "اطلاعات سرور",
    countryLabel = "موقعیت",
    uptimeLabel = "مدت اتصال",
    connectedToFormat = "متصل به %s",
    reconnectingFormat = "در حال اتصال به %s…",
    serversRefreshedFormat = "%d سرور به‌روزرسانی شد",
    serversRefreshFailed = "خطا در به‌روزرسانی سرورها. اینترنت را بررسی کنید.",
    customConfigImported = "پیکربندی سرور با موفقیت وارد شد!",
    vpnPermissionRequired = "مجوز VPN مورد نیاز است.",
    logCopiedToClipboard = "گزارش‌ها در حافظه کپی شد",
    privacyVerifiedBadgeTitle = "سیاست تأییدشده بدون لاگ",
    privacyVerifiedBadgeSubtitle = "تضمین صفر درصد جمع‌آوری اطلاعات",
    privacySection1Title = "۱. عدم ذخیره لاگ",
    privacySection1Content = "هیچ‌گونه لاگی از فعالیت‌های شما در اینترنت نگهداری نمی‌شود.",
    privacySection2Title = "۲. تونل‌سازی OpenVPN",
    privacySection2Content = "تمام ترافیک از طریق تونل امن رمزگذاری‌شده منتقل می‌شود.",
    privacySection3Title = "۳. رمزگذاری AES-256-GCM",
    privacySection3Content = "بالاترین سطح رمزگذاری برای حفاظت از داده‌های شما.",
    privacySection4Title = "۴. داده‌ها فقط در حافظه رم (RAM)",
    privacySection4Content = "آمار مصرف ترافیک تنها در رم نگهداری شده و با قطع اتصال پاک می‌شود.",
    privacySection5Title = "۵. عدم فروش داده‌ها",
    privacySection5Content = "اطلاعات شما تحت هیچ شرایطی به شخص ثالث فروخته نخواهد شد.",
    privacySection6Title = "۶. ارتباط با ما",
    privacySection6Content = "پشتیبانی: support@fastvpn.app",
    privacyAcceptButton = "متوجه شدم و موافقم",
    dataSafetySummaryTitle = "خلاصه ایمنی داده‌ها",
    dataCollectionTitle = "جمع‌آوری داده",
    dataCollectionValue = "هیچ (۰٪)",
    dataSharingTitle = "اشتراک داده‌ها",
    dataSharingValue = "هرگز (۰٪)",
    dataTransitTitle = "رمزگذاری در مسیر",
    dataTransitValue = "کاملاً رمزگذاری‌شده",
    dataDeletionTitle = "حذف داده‌ها",
    dataDeletionValue = "هیچ داده‌ای ذخیره نمی‌شود",
    dataCategoriesTitle = "دسته‌بندی داده‌ها",
    catLocationTitle = "موقعیت دقیق جغرافیایی",
    catLocationStatus = "هرگز ثبت نمی‌شود",
    catPersonalTitle = "اطلاعات هویتی",
    catPersonalStatus = "درخواست نمی‌شود",
    catBrowsingTitle = "تاریخچه مرورگر",
    catBrowsingStatus = "بدون هیچ گزارشی",
    catDeviceTitle = "شناسه‌های دستگاه",
    catDeviceStatus = "خوانده نمی‌شود",
    catThroughputTitle = "ترافیک زنده",
    catThroughputStatus = "فقط در رم در زمان اتصال",
    dataImpactTitle = "تأثیر بر مصرف اینترنت",
    dataImpactContent = "رمزگذاری OpenVPN حدود ۴ الی ۷ درصد به حجم بسته‌ها اضافه می‌کند. برنامه هیچ بارگیری پنهانی در پس‌زمینه ندارد.",
    netPermTitle = "دسترسی اینترنت",
    netPermStatus = "اعطا شده به صورت خودکار",
    netPermDesc = "برای دانلود سرورها و برقراری تونل ضروری است.",
    logsDialogTitle = "گزارش زنده OpenVPN",
    noLogsAvailable = "هنوز گزارشی ثبت نشده است…",
    copyButton = "کپی",
    clearButton = "پاک‌سازی",
    systemDefaultName = "پیش‌فرض سیستم",
    systemDefaultSubtitle = "خودکار بر اساس زبان دستگاه",
    filterFavorites = "علاقه‌مندی‌ها ⭐",
    noFavoritesFound = "هنوز سرور برگزیده‌ای اضافه نشده است",
    udpFastLabel = "OpenVPN UDP (سریع‌تر)",
    tcpStableLabel = "OpenVPN TCP (پایدارتر)",
    customConfigImportTitle = "وارد کردن فایل .ovpn",
    customConfigTitle = "افزودن سرور دلخواه",
    customConfigNamePlaceholder = "نام سرور",
    customConfigContentPlaceholder = "محتوای فایل .ovpn را اینجا جای‌گذاری کنید…",
    saveAndUseBtn = "ذخیره و استفاده",
    freeGuaranteeBadge = "۱۰۰٪ رایگان بدون هیچ‌گونه هزینه یا اشتراک",
    securityProtocolSettingsTitle = "امنیت و پروتکل",
    favoriteServerAction = "افزودن به علاقه‌مندی‌ها",
    selectedServerAction = "انتخاب شده",
    autoServerBadge = "خودکار"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    val effectiveLanguage = AppLanguage.resolveEffectiveLanguage(language)
    return when (effectiveLanguage) {
        AppLanguage.ARABIC -> ArabicStrings
        AppLanguage.PERSIAN -> PersianStrings
        AppLanguage.RUSSIAN -> RussianStrings
        AppLanguage.GERMAN -> GermanStrings
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.FRENCH -> FrenchStrings
        AppLanguage.SPANISH -> SpanishStrings
        AppLanguage.SYSTEM -> EnglishStrings // Resolved above, fallback here
    }
}
