package com.example.localization

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Bottom Navigation
    val navHome: String,
    val navServers: String,
    val navSettings: String,

    // Home Screen
    val appTitle: String,
    val statusConnected: String,
    val statusDisconnected: String,
    val statusConnecting: String,
    val statusReconnecting: String,
    val tapToConnect: String,
    val tapToDisconnect: String,
    val tapToCancel: String,
    val optimalServer: String,
    val optimalServerDesc: String,
    val selectServerTitle: String,
    val download: String,
    val upload: String,
    val ping: String,
    val duration: String,
    val ipAddress: String,
    val protocolLabel: String,
    val connectionProtected: String,
    val notProtected: String,
    val freeAndFastBadge: String,

    // Servers / Locations Screen
    val serversTitle: String,
    val serversSubtitle: String,
    val searchPlaceholder: String,
    val refreshServers: String,
    val filterAll: String,
    val filterFast: String,
    val filterLowPing: String,
    val noServersFound: String,
    val serverCountFormat: String,

    // Settings Screen
    val settingsTitle: String,
    val settingsSubtitle: String,
    val vpnSecurityCategory: String,
    val autoConnectTitle: String,
    val autoConnectSubtitle: String,
    val killSwitchTitle: String,
    val killSwitchSubtitle: String,
    val dnsLeakTitle: String,
    val dnsLeakSubtitle: String,
    val notificationsTitle: String,
    val notificationsSubtitle: String,
    val preferencesCategory: String,
    val protocolTitle: String,
    val languageTitle: String,
    val appearanceTitle: String,
    val appearanceLight: String,
    val advancedCategory: String,
    val connectionLogsTitle: String,
    val viewLiveLogs: String,
    val aboutAppTitle: String,
    val helpSupportTitle: String,
    val versionFree: String,

    // Compliance Category in Settings
    val complianceCategory: String,
    val privacyPolicyTitle: String,
    val privacyPolicySubtitle: String,
    val dataSafetyTitle: String,
    val dataSafetySubtitle: String,
    val vpnDisclosureTitle: String,
    val vpnDisclosureSubtitle: String,
    val appPermissionsTitle: String,
    val appPermissionsSubtitle: String,

    // Language Selector Dialog
    val chooseLanguageTitle: String,
    val chooseLanguageSubtitle: String,
    val applyLanguageBtn: String,
    val cancelBtn: String,
    val closeBtn: String,

    // Prominent Disclosure Dialog
    val disclosureTitle: String,
    val disclosureSubtitle: String,
    val disclosurePoint1Title: String,
    val disclosurePoint1Desc: String,
    val disclosurePoint2Title: String,
    val disclosurePoint2Desc: String,
    val disclosurePoint3Title: String,
    val disclosurePoint3Desc: String,
    val agreeAndContinueBtn: String,
    val viewPrivacyPolicyLink: String,
    val viewDataSafetyLink: String,

    // Privacy Policy Dialog
    val privacyPolicyHeader: String,
    val privacyZeroLogsTitle: String,
    val privacyZeroLogsDesc: String,
    val privacyVpnServiceTitle: String,
    val privacyVpnServiceDesc: String,
    val privacySecurityTitle: String,
    val privacySecurityDesc: String,
    val privacyNoSaleTitle: String,
    val privacyNoSaleDesc: String,

    // Data Safety Dialog
    val dataSafetyHeader: String,
    val dataSafetySubheader: String,
    val noDataCollected: String,
    val noDataShared: String,
    val encryptedInTransit: String,
    val overheadNoticeTitle: String,
    val overheadNoticeDesc: String,

    // Permissions Dialog
    val permissionsHeader: String,
    val permissionsSubheader: String,
    val permissionsIntro: String,
    val vpnKeyPermTitle: String,
    val vpnKeyPermStatus: String,
    val vpnKeyPermDesc: String,
    val notifPermTitle: String,
    val notifPermGranted: String,
    val notifPermRequired: String,
    val notifPermDesc: String,
    val grantPermBtn: String,
    val openSettingsBtn: String,

    // Onboarding Dialog
    val onboardingTitle: String,
    val onboardingSubtitle: String,
    val freeFeatureTitle: String,
    val freeFeatureSubtitle: String,
    val noRegFeatureTitle: String,
    val noRegFeatureSubtitle: String,
    val secureFeatureTitle: String,
    val secureFeatureSubtitle: String,
    val onboardingDisclaimer: String,
    val onboardingContinueBtn: String,

    // Connection Details Dialog
    val connectionDetailsTitle: String,
    val sessionStatsTitle: String,
    val serverDetailsTitle: String,
    val countryLabel: String,
    val uptimeLabel: String
)

val LocalAppStrings = compositionLocalOf { EnglishStrings }

val EnglishStrings = AppStrings(
    navHome = "Home",
    navServers = "Servers",
    navSettings = "Settings",

    appTitle = "OpenVPN Free",
    statusConnected = "Connected & Secured",
    statusDisconnected = "Disconnected",
    statusConnecting = "Connecting…",
    statusReconnecting = "Switching Server…",
    tapToConnect = "Tap to Connect",
    tapToDisconnect = "Tap to Disconnect",
    tapToCancel = "Cancel",
    optimalServer = "Fastest Server (Auto)",
    optimalServerDesc = "Optimal location based on latency",
    selectServerTitle = "Select Location",
    download = "Download",
    upload = "Upload",
    ping = "Ping",
    duration = "Duration",
    ipAddress = "IP Address",
    protocolLabel = "Protocol",
    connectionProtected = "Your internet connection is encrypted",
    notProtected = "You are currently unprotected",
    freeAndFastBadge = "Free & Unlimited",

    serversTitle = "VPN Servers",
    serversSubtitle = "Global high-speed OpenVPN servers",
    searchPlaceholder = "Search by country or city…",
    refreshServers = "Refresh",
    filterAll = "All",
    filterFast = "Fastest",
    filterLowPing = "Low Ping",
    noServersFound = "No servers found matching your query",
    serverCountFormat = "%d servers available (1 per country)",

    settingsTitle = "Settings",
    settingsSubtitle = "Security, tunneling & preferences",
    vpnSecurityCategory = "VPN Security & Tunneling",
    autoConnectTitle = "Auto-connect",
    autoConnectSubtitle = "Connect automatically on app launch",
    killSwitchTitle = "Kill Switch",
    killSwitchSubtitle = "Block internet if VPN connection drops",
    dnsLeakTitle = "DNS Leak Protection",
    dnsLeakSubtitle = "Enforce private encrypted DNS queries",
    notificationsTitle = "Notifications",
    notificationsSubtitle = "Connection status & disconnect quick action",
    preferencesCategory = "Preferences",
    protocolTitle = "Protocol",
    languageTitle = "Language",
    appearanceTitle = "App Appearance",
    appearanceLight = "Light",
    advancedCategory = "Advanced & Logs",
    connectionLogsTitle = "Connection Logs",
    viewLiveLogs = "View Live OpenVPN Logs",
    aboutAppTitle = "About Fast VPN",
    helpSupportTitle = "Help & Support",
    versionFree = "v1.0.0 (100% Free)",

    complianceCategory = "Privacy & Google Play Compliance",
    privacyPolicyTitle = "Privacy Policy",
    privacyPolicySubtitle = "Strict Zero-Logs Policy",
    dataSafetyTitle = "Data Safety & Security",
    dataSafetySubtitle = "Google Play Safety Standards",
    vpnDisclosureTitle = "VPN Service Disclosure",
    vpnDisclosureSubtitle = "VpnService Policy Compliance",
    appPermissionsTitle = "App Permissions & Transparency",
    appPermissionsSubtitle = "Permission controls and rationale",

    chooseLanguageTitle = "Choose Language",
    chooseLanguageSubtitle = "Select your preferred app display language",
    applyLanguageBtn = "Apply",
    cancelBtn = "Cancel",
    closeBtn = "Close",

    disclosureTitle = "VPN Service & Privacy Disclosure",
    disclosureSubtitle = "In accordance with Google Play VPN policies, here is how our service operates to protect your privacy before you connect.",
    disclosurePoint1Title = "Core Android VpnService Usage",
    disclosurePoint1Desc = "This app uses Android's VpnService exclusively to create a secure device-level encrypted tunnel that routes your traffic safely.",
    disclosurePoint2Title = "Strict Zero-Logs Guarantee",
    disclosurePoint2Desc = "We never track, store, or sell your browsing history, DNS queries, real IP address, or any personal data.",
    disclosurePoint3Title = "Ephemeral Session Traffic Stats",
    disclosurePoint3Desc = "Download and upload statistics are calculated locally in device RAM only during active sessions and cleared immediately upon disconnect.",
    agreeAndContinueBtn = "Agree & Continue",
    viewPrivacyPolicyLink = "📜 Privacy Policy",
    viewDataSafetyLink = "🛡️ Data Safety",

    privacyPolicyHeader = "Privacy Policy",
    privacyZeroLogsTitle = "1. Strict Zero-Logs Guarantee",
    privacyZeroLogsDesc = "We uphold a strict zero-logs commitment. We do NOT record, log, monitor, or store: your real IP address, DNS requests, visited websites, connection timestamps, or session content.",
    privacyVpnServiceTitle = "2. Google Play VpnService Compliance",
    privacyVpnServiceDesc = "Our app uses Android's official VpnService strictly as a secure encrypted tunnel. We do NOT inject ads, tamper with unencrypted traffic, or perform surveillance.",
    privacySecurityTitle = "3. End-to-End Encryption Standards",
    privacySecurityDesc = "All traffic passing through the tunnel is encrypted using OpenVPN with AES-256-GCM cipher and TLS 1.3 key exchange, shielding your traffic on public Wi-Fi networks.",
    privacyNoSaleTitle = "4. No Data Selling or Third-Party Sharing",
    privacyNoSaleDesc = "We do not sell, rent, monetize, or disclose any user information to data brokers, advertisers, or third parties.",

    dataSafetyHeader = "Data Safety & Security",
    dataSafetySubheader = "Transparency report aligned with Google Play Console requirements",
    noDataCollected = "No Data Collected",
    noDataShared = "No Data Shared",
    encryptedInTransit = "Encrypted in Transit",
    overheadNoticeTitle = "Understanding Data Overhead with VPN",
    overheadNoticeDesc = "Due to cryptographic headers and IP encapsulation, you may notice a 5-15% increase in cellular data usage. This is standard across all secure VPN protocols.",

    permissionsHeader = "App Permissions & Transparency",
    permissionsSubheader = "Minimal privilege policy compliance",
    permissionsIntro = "Our app requests only the minimum technical permissions required to provide a safe VPN tunnel.",
    vpnKeyPermTitle = "VPN Service Permission (VpnService)",
    vpnKeyPermStatus = "Standard System Permission",
    vpnKeyPermDesc = "Handled automatically via Android's secure confirmation dialog on first connection.",
    notifPermTitle = "Notification Permission (Foreground Service)",
    notifPermGranted = "Granted & Active",
    notifPermRequired = "Required for Status Bar",
    notifPermDesc = "Allows displaying a persistent notification to monitor tunnel status and disconnect instantly.",
    grantPermBtn = "Grant Permission",
    openSettingsBtn = "Open App Settings in Android",

    onboardingTitle = "Fast VPN",
    onboardingSubtitle = "Fast, simple, secure VPN. A more private and open internet for everyone.",
    freeFeatureTitle = "Free access",
    freeFeatureSubtitle = "No payment required. 100% free forever.",
    noRegFeatureTitle = "No registration & Zero logs",
    noRegFeatureSubtitle = "Start using instantly. No email or account needed.",
    secureFeatureTitle = "Secure connection",
    secureFeatureSubtitle = "Protect your online activity with AES-256.",
    onboardingDisclaimer = "By continuing, you accept our Privacy Policy & Data Safety standards.",
    onboardingContinueBtn = "Continue",

    connectionDetailsTitle = "Connection Details",
    sessionStatsTitle = "Session Statistics",
    serverDetailsTitle = "Server Details",
    countryLabel = "Country",
    uptimeLabel = "Uptime"
)

val ArabicStrings = AppStrings(
    navHome = "الرئيسية",
    navServers = "الخوادم",
    navSettings = "الإعدادات",

    appTitle = "OpenVPN Free",
    statusConnected = "متصل بأمان",
    statusDisconnected = "غير متصل",
    statusConnecting = "جاري الاتصال…",
    statusReconnecting = "جاري التبديل للخادم الجديد…",
    tapToConnect = "انقر للاتصال",
    tapToDisconnect = "انقر لقطع الاتصال",
    tapToCancel = "إلغاء",
    optimalServer = "أسرع خادم (تلقائي)",
    optimalServerDesc = "الموقع الأفضل استناداً لسرعة الاستجابة",
    selectServerTitle = "اختيار الدولة",
    download = "تحميل",
    upload = "رفع",
    ping = "الاستجابة",
    duration = "المدة",
    ipAddress = "عنوان IP",
    protocolLabel = "البروتوكول",
    connectionProtected = "اتصال الإنترنت الخاص بك مشفر وآمن",
    notProtected = "أنت غير محمي حالياً",
    freeAndFastBadge = "مجاني وغير محدود",

    serversTitle = "قائمة خوادم الـ VPN",
    serversSubtitle = "خوادم OpenVPN مجانية وسريعة حول العالم",
    searchPlaceholder = "ابحث بالدولة أو المدينة…",
    refreshServers = "تحديث",
    filterAll = "الكل",
    filterFast = "الأسرع",
    filterLowPing = "استجابة ممتازة",
    noServersFound = "لا توجد خوادم مطابقة للبحث",
    serverCountFormat = "%d خادم متوفر (خادم واحد لكل دولة)",

    settingsTitle = "الإعدادات",
    settingsSubtitle = "الأمان، الاتصال وتفضيلات التطبيق",
    vpnSecurityCategory = "أمان وتشفير اتصال الـ VPN",
    autoConnectTitle = "الاتصال التلقائي",
    autoConnectSubtitle = "الاتصال تلقائياً عند فتح التطبيق",
    killSwitchTitle = "مفتاح الإيقاف التلقائي (Kill Switch)",
    killSwitchSubtitle = "حظر الإنترنت تلقائياً في حال انقطاع الـ VPN",
    dnsLeakTitle = "حماية تسرب DNS",
    dnsLeakSubtitle = "فرض استعلامات DNS خاصة ومشفرة دائماً",
    notificationsTitle = "الإشعارات والتنبيهات",
    notificationsSubtitle = "إشعار دائم لعرض السرعة وزر قطع الاتصال السريع",
    preferencesCategory = "التفضيلات واللغة",
    protocolTitle = "نوع البروتوكول",
    languageTitle = "لغة التطبيق",
    appearanceTitle = "مظهر التطبيق",
    appearanceLight = "فاتح",
    advancedCategory = "متقدم وسجلات الاتصال",
    connectionLogsTitle = "سجلات الاتصال المباشرة",
    viewLiveLogs = "عرض سجلات OpenVPN اللحظية",
    aboutAppTitle = "حول تطبيق Fast VPN",
    helpSupportTitle = "المساعدة والدعم",
    versionFree = "v1.0.0 (مجاني 100%)",

    complianceCategory = "الخصوصية والامتثال لـ Google Play",
    privacyPolicyTitle = "سياسة الخصوصية",
    privacyPolicySubtitle = "سياسة صارمة لمنع السجلات",
    dataSafetyTitle = "أمان واستخدام البيانات",
    dataSafetySubtitle = "معايير سلامة بيانات Google Play",
    vpnDisclosureTitle = "إفصاح خدمة الـ VPN",
    vpnDisclosureSubtitle = "الامتثال لسياسة VpnService",
    appPermissionsTitle = "أذونات التطبيق والشفافية",
    appPermissionsSubtitle = "إدارة وتبرير الأذونات المطلوبة",

    chooseLanguageTitle = "اختر لغة التطبيق",
    chooseLanguageSubtitle = "حدد اللغة المفضلة لواجهات التطبيق",
    applyLanguageBtn = "تطبيق",
    cancelBtn = "إلغاء",
    closeBtn = "إغلاق",

    disclosureTitle = "إفصاح خدمة الـ VPN والخصوصية",
    disclosureSubtitle = "وفقاً لسياسات Google Play المتعلقة بخدمات VPN، نوضح لك طبيعة عمل الخدمة وكيفية حماية بياناتك قبل تفعيل الاتصال.",
    disclosurePoint1Title = "استخدام خدمة VpnService الأساسية",
    disclosurePoint1Desc = "يستخدم التطبيق واجهة VpnService من أندرويد فقط لإنشاء نفق تشفير آمن على مستوى الجهاز لحماية اتصالك وتوجيه البيانات بأمان.",
    disclosurePoint2Title = "سياسة صارمة لمنع السجلات (Zero-Logs)",
    disclosurePoint2Desc = "لا نسجل، لا نراقب، ولا نبيع سجل تصفحك أو استعلامات DNS أو عنوان IP الحقيقي الخاص بك أو أي بيانات شخصية.",
    disclosurePoint3Title = "إحصائيات الجلسة اللحظية",
    disclosurePoint3Desc = "يتم حساب سرعة التنزيل والرفع محلياً في ذاكرة الجهاز (RAM) فقط لعرضها أثناء الاتصال، ويتم مسحها فوراً عند قطع الاتصال.",
    agreeAndContinueBtn = "أوافق وأتابع (Agree & Continue)",
    viewPrivacyPolicyLink = "📜 سياسة الخصوصية",
    viewDataSafetyLink = "🛡️ أمان واستخدام البيانات",

    privacyPolicyHeader = "سياسة الخصوصية",
    privacyZeroLogsTitle = "1. سياسة صارمة لمنع السجلات (Zero-Logs)",
    privacyZeroLogsDesc = "نلتزم التزاماً كاملاً بعدم تسجيل أو مراقبة أو تخزين أي نشاط للمستخدم: لا نسجل عنوان IP الحقيقي، ولا استعلامات DNS، ولا المواقع التي تزورها، ولا أوقات الاتصال، ولا محتوى البيانات.",
    privacyVpnServiceTitle = "2. الامتثال لسياسات VpnService في Google Play",
    privacyVpnServiceDesc = "نستخدم VpnService الرسمية لأغراض الحماية والتشفير المشروع فقط، ولا نستخدم النفق للتلاعب بالحزم أو حقن الإعلانات أو جمع البيانات.",
    privacySecurityTitle = "3. معايير التشفير والأمان الفائق",
    privacySecurityDesc = "تشفير كامل لجميع البيانات عبر بروتوكول OpenVPN وخوارزمية AES-256-GCM وتبادل مفاتيح TLS 1.3 مع حماية تسرب DNS.",
    privacyNoSaleTitle = "4. عدم مشاركة أو بيع البيانات لأطراف ثالثة",
    privacyNoSaleDesc = "لا نقوم بمشاركة أو بيع أو تأجير أي بيانات لأطراف ثالثة أو شركات تسويق أو وسطاء بيانات نهائياً.",

    dataSafetyHeader = "أمان واستخدام البيانات (Data Safety)",
    dataSafetySubheader = "تقرير الشفافية الرسمي المتوافق مع متطلبات Google Play Console",
    noDataCollected = "لا يتم جمع أي بيانات",
    noDataShared = "لا يتم مشاركة أي بيانات",
    encryptedInTransit = "مشفر بالكامل أثناء النقل",
    overheadNoticeTitle = "تنويه حول استهلاك البيانات أثناء تشغيل الـ VPN",
    overheadNoticeDesc = "بسبب ترويسات التشفير الأمنية لكل حزمة، قد تلاحظ زيادة بنسبة 5-15% في استهلاك باقة الإنترنت، وهو أمر قياسي في جميع بروتوكولات الـ VPN الآمنة.",

    permissionsHeader = "أذونات التطبيق والشفافية",
    permissionsSubheader = "وفق معايير الحد الأدنى من الأذونات",
    permissionsIntro = "يطلب التطبيق فقط الأذونات الضرورية تقنياً لتشغيل نفق الـ VPN بأمان وفق سياسات Google Play.",
    vpnKeyPermTitle = "إذن خدمة الـ VPN (VpnService)",
    vpnKeyPermStatus = "إذن نظام معتمد",
    vpnKeyPermDesc = "يتم طلبه تلقائياً عبر نافذة حماية نظام Android عند أول اتصال لإنشاء النفق المشفر بأمان.",
    notifPermTitle = "إذن الإشعارات (Foreground Service)",
    notifPermGranted = "ممنوح ومفعل",
    notifPermRequired = "مطلوب لتنبيهات الاتصال",
    notifPermDesc = "مطلوب لإبقاء إشعار دائم في شريط الحالة أثناء عمل الـ VPN لتمكينك من متابعة سرعة النفق وإيقافه فوراً بنقرة واحدة.",
    grantPermBtn = "تفعيل الإذن",
    openSettingsBtn = "فتح إعدادات التطبيق في النظام",

    onboardingTitle = "Fast VPN",
    onboardingSubtitle = "تطبيق VPN سريع، بسيط وآمن لإنترنت مفتوح ومحمي للجميع.",
    freeFeatureTitle = "وصول مجاني 100%",
    freeFeatureSubtitle = "بدون أي رسوم أو اشتراكات شهرية.",
    noRegFeatureTitle = "بدون تسجيل وبدون سجلات",
    noRegFeatureSubtitle = "ابدأ الاستخدام فوراً بدون بريد أو حساب شخصي.",
    secureFeatureTitle = "اتصال مشفر وآمن",
    secureFeatureSubtitle = "حماية كاملة لنشاطك على الإنترنت بتشفير AES-256.",
    onboardingDisclaimer = "بالاستمرار، أنت توافق على سياسة الخصوصية ومعايير أمان البيانات.",
    onboardingContinueBtn = "متابعة",

    connectionDetailsTitle = "تفاصيل الاتصال",
    sessionStatsTitle = "إحصائيات الجلسة",
    serverDetailsTitle = "بيانات الخادم",
    countryLabel = "الدولة",
    uptimeLabel = "وقت التشغيل"
)

val FrenchStrings = AppStrings(
    navHome = "Accueil",
    navServers = "Serveurs",
    navSettings = "Paramètres",

    appTitle = "OpenVPN Free",
    statusConnected = "Connecté et Sécurisé",
    statusDisconnected = "Déconnecté",
    statusConnecting = "Connexion en cours…",
    statusReconnecting = "Changement de serveur…",
    tapToConnect = "Appuyer pour se connecter",
    tapToDisconnect = "Appuyer pour déconnecter",
    tapToCancel = "Annuler",
    optimalServer = "Serveur le plus rapide (Auto)",
    optimalServerDesc = "Emplacement optimal selon la latence",
    selectServerTitle = "Choisir l'emplacement",
    download = "Téléchargement",
    upload = "Envoi",
    ping = "Ping",
    duration = "Durée",
    ipAddress = "Adresse IP",
    protocolLabel = "Protocole",
    connectionProtected = "Votre connexion est chiffrée et sécurisée",
    notProtected = "Vous n'êtes pas protégé actuellement",
    freeAndFastBadge = "Gratuit et Illimité",

    serversTitle = "Serveurs VPN",
    serversSubtitle = "Serveurs OpenVPN haut débit à travers le monde",
    searchPlaceholder = "Rechercher un pays ou une ville…",
    refreshServers = "Actualiser",
    filterAll = "Tous",
    filterFast = "Plus rapides",
    filterLowPing = "Faible latence",
    noServersFound = "Aucun serveur trouvé pour cette recherche",
    serverCountFormat = "%d serveurs disponibles (1 par pays)",

    settingsTitle = "Paramètres",
    settingsSubtitle = "Sécurité, tunneling et préférences",
    vpnSecurityCategory = "Sécurité et Tunneling VPN",
    autoConnectTitle = "Connexion automatique",
    autoConnectSubtitle = "Se connecter au lancement de l'application",
    killSwitchTitle = "Bouton d'arrêt d'urgence (Kill Switch)",
    killSwitchSubtitle = "Bloquer Internet en cas de coupure VPN",
    dnsLeakTitle = "Protection contre les fuites DNS",
    dnsLeakSubtitle = "Appliquer des requêtes DNS privées et chiffrées",
    notificationsTitle = "Notifications",
    notificationsSubtitle = "Statut de connexion et déconnexion rapide",
    preferencesCategory = "Préférences et Langue",
    protocolTitle = "Protocole",
    languageTitle = "Langue de l'application",
    appearanceTitle = "Apparence",
    appearanceLight = "Clair",
    advancedCategory = "Avancé et Journaux",
    connectionLogsTitle = "Journaux de connexion",
    viewLiveLogs = "Voir les journaux OpenVPN en direct",
    aboutAppTitle = "À propos de Fast VPN",
    helpSupportTitle = "Aide et Support",
    versionFree = "v1.0.0 (100% Gratuit)",

    complianceCategory = "Confidentialité et Conformité Google Play",
    privacyPolicyTitle = "Politique de confidentialité",
    privacyPolicySubtitle = "Politique stricte sans journaux (Zero-Logs)",
    dataSafetyTitle = "Sécurité et Utilisation des données",
    dataSafetySubtitle = "Normes de sécurité Google Play",
    vpnDisclosureTitle = "Divulgation du service VPN",
    vpnDisclosureSubtitle = "Conformité à la politique VpnService",
    appPermissionsTitle = "Autorisations et Transparence",
    appPermissionsSubtitle = "Gestion et justification des autorisations",

    chooseLanguageTitle = "Choisir la langue",
    chooseLanguageSubtitle = "Sélectionnez la langue d'affichage souhaitée",
    applyLanguageBtn = "Appliquer",
    cancelBtn = "Annuler",
    closeBtn = "Fermer",

    disclosureTitle = "Divulgation du service VPN et Confidentialité",
    disclosureSubtitle = "Conformément aux règles de Google Play pour les applications VPN, voici comment fonctionne notre service pour protéger votre vie privée avant la connexion.",
    disclosurePoint1Title = "Utilisation du service VpnService d'Android",
    disclosurePoint1Desc = "L'application utilise l'interface officielle VpnService d'Android uniquement pour établir un tunnel chiffré au niveau de l'appareil.",
    disclosurePoint2Title = "Garantie stricte sans journaux (Zero-Logs)",
    disclosurePoint2Desc = "Nous n'enregistrons, ne surveillons et ne vendons jamais votre historique de navigation, vos requêtes DNS, votre adresse IP réelle ou vos données personnelles.",
    disclosurePoint3Title = "Statistiques de trafic de session éphémères",
    disclosurePoint3Desc = "Les débits de téléchargement et d'envoi sont calculés localement dans la mémoire vive (RAM) uniquement pendant la session et supprimés à la déconnexion.",
    agreeAndContinueBtn = "Accepter et Continuer",
    viewPrivacyPolicyLink = "📜 Politique de confidentialité",
    viewDataSafetyLink = "🛡️ Sécurité des données",

    privacyPolicyHeader = "Politique de confidentialité",
    privacyZeroLogsTitle = "1. Engagement strict sans journaux (Zero-Logs)",
    privacyZeroLogsDesc = "Nous appliquons une politique stricte d'absence de journaux. Nous n'enregistrons, ne stockons ni ne surveillons votre adresse IP réelle, vos requêtes DNS, vos sites visités ou le contenu de vos échanges.",
    privacyVpnServiceTitle = "2. Conformité VpnService de Google Play",
    privacyVpnServiceDesc = "Notre application utilise le service officiel VpnService à des fins légitimes de chiffrement. Nous n'injectons aucune publicité et ne modifions pas votre trafic.",
    privacySecurityTitle = "3. Normes de chiffrement de haut niveau",
    privacySecurityDesc = "Tout le trafic est chiffré avec OpenVPN et l'algorithme AES-256-GCM avec échange de clés TLS 1.3 et protection contre les fuites DNS.",
    privacyNoSaleTitle = "4. Aucune vente ni partage de données avec des tiers",
    privacyNoSaleDesc = "Nous ne vendons, ne louons et ne transmettons aucune information utilisateur à des courtiers en données ou des tiers publicitaires.",

    dataSafetyHeader = "Sécurité des données (Data Safety)",
    dataSafetySubheader = "Rapport de transparence aligné sur les exigences de Google Play Console",
    noDataCollected = "Aucune donnée collectée",
    noDataShared = "Aucune donnée partagée",
    encryptedInTransit = "Chiffré en transit",
    overheadNoticeTitle = "Consommation de données avec le VPN",
    overheadNoticeDesc = "En raison des en-têtes de chiffrement et de l'encapsulation IP, vous pouvez observer une augmentation de 5 à 15 % de la consommation de données cellulaires, ce qui est standard pour les VPN sécurisés.",

    permissionsHeader = "Autorisations de l'application",
    permissionsSubheader = "Respect du principe du moindre privilège",
    permissionsIntro = "Notre application ne demande que les autorisations strictement requises techniquement pour établir le tunnel VPN en toute sécurité.",
    vpnKeyPermTitle = "Autorisation VpnService",
    vpnKeyPermStatus = "Autorisation système standard",
    vpnKeyPermDesc = "Gérée automatiquement via la boîte de dialogue de sécurité d'Android lors de la première connexion.",
    notifPermTitle = "Autorisation de notification (Service de premier plan)",
    notifPermGranted = "Accordée et active",
    notifPermRequired = "Requise pour la barre d'état",
    notifPermDesc = "Nécessaire pour afficher une notification permanente indiquant l'état du tunnel et permettant de se déconnecter en un clic.",
    grantPermBtn = "Accorder l'autorisation",
    openSettingsBtn = "Ouvrir les paramètres système",

    onboardingTitle = "Fast VPN",
    onboardingSubtitle = "Un VPN rapide, simple et sécurisé pour un Internet plus privé et ouvert à tous.",
    freeFeatureTitle = "Accès 100% gratuit",
    freeFeatureSubtitle = "Aucun paiement requis. Gratuit pour toujours.",
    noRegFeatureTitle = "Sans inscription & Sans journaux",
    noRegFeatureSubtitle = "Commencez instantanément sans email ni compte requis.",
    secureFeatureTitle = "Connexion sécurisée",
    secureFeatureSubtitle = "Protégez votre activité en ligne avec le chiffrement AES-256.",
    onboardingDisclaimer = "En continuant, vous acceptez notre politique de confidentialité et nos règles de sécurité des données.",
    onboardingContinueBtn = "Continuer",

    connectionDetailsTitle = "Détails de la connexion",
    sessionStatsTitle = "Statistiques de la session",
    serverDetailsTitle = "Informations du serveur",
    countryLabel = "Pays",
    uptimeLabel = "Temps de connexion"
)

val SpanishStrings = AppStrings(
    navHome = "Inicio",
    navServers = "Servidores",
    navSettings = "Ajustes",

    appTitle = "OpenVPN Free",
    statusConnected = "Conectado y Seguro",
    statusDisconnected = "Desconectado",
    statusConnecting = "Conectando…",
    statusReconnecting = "Cambiando de servidor…",
    tapToConnect = "Tocar para conectar",
    tapToDisconnect = "Tocar para desconectar",
    tapToCancel = "Cancelar",
    optimalServer = "Servidor más rápido (Auto)",
    optimalServerDesc = "Ubicación óptima según la latencia",
    selectServerTitle = "Seleccionar ubicación",
    download = "Descarga",
    upload = "Subida",
    ping = "Ping",
    duration = "Duración",
    ipAddress = "Dirección IP",
    protocolLabel = "Protocolo",
    connectionProtected = "Tu conexión a Internet está cifrada y segura",
    notProtected = "Actualmente no estás protegido",
    freeAndFastBadge = "Gratis e Ilimitado",

    serversTitle = "Servidores VPN",
    serversSubtitle = "Servidores OpenVPN de alta velocidad en todo el mundo",
    searchPlaceholder = "Buscar país o ciudad…",
    refreshServers = "Actualizar",
    filterAll = "Todos",
    filterFast = "Más rápidos",
    filterLowPing = "Ping bajo",
    noServersFound = "No se encontraron servidores con este criterio",
    serverCountFormat = "%d servidores disponibles (1 por país)",

    settingsTitle = "Ajustes",
    settingsSubtitle = "Seguridad, túneles y preferencias",
    vpnSecurityCategory = "Seguridad y Túnel VPN",
    autoConnectTitle = "Conexión automática",
    autoConnectSubtitle = "Conectar automáticamente al abrir la app",
    killSwitchTitle = "Interruptor de corte (Kill Switch)",
    killSwitchSubtitle = "Bloquear Internet si la conexión VPN se interrumpe",
    dnsLeakTitle = "Protección contra fugas DNS",
    dnsLeakSubtitle = "Forzar consultas DNS privadas y cifradas",
    notificationsTitle = "Notificaciones",
    notificationsSubtitle = "Estado de conexión y desconexión rápida",
    preferencesCategory = "Preferencias e Idioma",
    protocolTitle = "Protocolo",
    languageTitle = "Idioma de la aplicación",
    appearanceTitle = "Apariencia",
    appearanceLight = "Claro",
    advancedCategory = "Avanzado y Registros",
    connectionLogsTitle = "Registros de conexión",
    viewLiveLogs = "Ver registros de OpenVPN en vivo",
    aboutAppTitle = "Acerca de Fast VPN",
    helpSupportTitle = "Ayuda y Soporte",
    versionFree = "v1.0.0 (100% Gratis)",

    complianceCategory = "Privacidad y Cumplimiento Google Play",
    privacyPolicyTitle = "Política de privacidad",
    privacyPolicySubtitle = "Política estricta sin registros (Zero-Logs)",
    dataSafetyTitle = "Seguridad y Uso de datos",
    dataSafetySubtitle = "Estándares de seguridad de Google Play",
    vpnDisclosureTitle = "Divulgación del servicio VPN",
    vpnDisclosureSubtitle = "Cumplimiento de la política VpnService",
    appPermissionsTitle = "Permisos y Transparencia",
    appPermissionsSubtitle = "Gestión y justificación de permisos",

    chooseLanguageTitle = "Elegir idioma",
    chooseLanguageSubtitle = "Selecciona tu idioma preferido para la app",
    applyLanguageBtn = "Aplicar",
    cancelBtn = "Cancelar",
    closeBtn = "Cerrar",

    disclosureTitle = "Divulgación del servicio VPN y Privacidad",
    disclosureSubtitle = "De acuerdo con las políticas de Google Play para apps VPN, así funciona nuestro servicio para proteger tu privacidad antes de conectarte.",
    disclosurePoint1Title = "Uso esencial de VpnService de Android",
    disclosurePoint1Desc = "La app utiliza la API oficial VpnService de Android exclusivamente para crear un túnel cifrado a nivel de dispositivo.",
    disclosurePoint2Title = "Garantía estricta sin registros (Zero-Logs)",
    disclosurePoint2Desc = "Nunca registramos, monitoreamos ni vendemos tu historial de navegación, consultas DNS, dirección IP real ni datos personales.",
    disclosurePoint3Title = "Estadísticas de sesión efímeras",
    disclosurePoint3Desc = "Las velocidades de subida y bajada se calculan localmente en la memoria RAM solo durante la sesión y se borran al desconectar.",
    agreeAndContinueBtn = "Aceptar y Continuar",
    viewPrivacyPolicyLink = "📜 Política de privacidad",
    viewDataSafetyLink = "🛡️ Seguridad de datos",

    privacyPolicyHeader = "Política de privacidad",
    privacyZeroLogsTitle = "1. Compromiso estricto sin registros (Zero-Logs)",
    privacyZeroLogsDesc = "Mantenemos una política estricta sin registros. NO registramos, guardamos ni monitoreamos: tu IP real, consultas DNS, sitios web visitados ni contenido de tráfico.",
    privacyVpnServiceTitle = "2. Cumplimiento de VpnService en Google Play",
    privacyVpnServiceDesc = "Nuestra app utiliza el servicio oficial VpnService únicamente como túnel cifrado seguro. No inyectamos anuncios ni alteramos tu tráfico.",
    privacySecurityTitle = "3. Estándares de cifrado de alta seguridad",
    privacySecurityDesc = "Todo el tráfico se cifra mediante OpenVPN con cifrado AES-256-GCM, intercambio de claves TLS 1.3 y protección contra fugas DNS.",
    privacyNoSaleTitle = "4. Sin venta ni cesión de datos a terceros",
    privacyNoSaleDesc = "No vendemos, alquilamos ni divulgamos información de usuarios a intermediarios de datos ni empresas publicitarias.",

    dataSafetyHeader = "Seguridad de datos (Data Safety)",
    dataSafetySubheader = "Informe de transparencia alineado con los requisitos de Google Play Console",
    noDataCollected = "No se recopilan datos",
    noDataShared = "No se comparten datos",
    encryptedInTransit = "Cifrado en tránsito",
    overheadNoticeTitle = "Consumo de datos con VPN",
    overheadNoticeDesc = "Debido al encabezado de cifrado y la encapsulación IP, podrías notar un aumento del 5 al 15% en el uso de datos móviles, lo cual es normal en todos los protocolos VPN seguros.",

    permissionsHeader = "Permisos de la aplicación",
    permissionsSubheader = "Cumplimiento del principio de privilegio mínimo",
    permissionsIntro = "Nuestra app solo solicita los permisos técnicos mínimos estrictamente necesarios para ofrecer un túnel VPN seguro.",
    vpnKeyPermTitle = "Permiso VpnService",
    vpnKeyPermStatus = "Permiso estándar del sistema",
    vpnKeyPermDesc = "Se solicita automáticamente mediante el diálogo de seguridad de Android en la primera conexión.",
    notifPermTitle = "Permiso de notificaciones (Servicio en primer plano)",
    notifPermGranted = "Concedido y activo",
    notifPermRequired = "Requerido para la barra de estado",
    notifPermDesc = "Permite mostrar una notificación persistente para monitorear el túnel y desconectarse con un solo toque.",
    grantPermBtn = "Conceder permiso",
    openSettingsBtn = "Abrir ajustes del sistema",

    onboardingTitle = "Fast VPN",
    onboardingSubtitle = "Una VPN rápida, sencilla y segura para un Internet más privado y abierto para todos.",
    freeFeatureTitle = "Acceso 100% gratuito",
    freeFeatureSubtitle = "Sin pagos requeridos. Totalmente gratis para siempre.",
    noRegFeatureTitle = "Sin registro y sin registros",
    noRegFeatureSubtitle = "Comienza al instante sin correo electrónico ni cuenta.",
    secureFeatureTitle = "Conexión segura",
    secureFeatureSubtitle = "Protege tu actividad en línea con cifrado AES-256.",
    onboardingDisclaimer = "Al continuar, aceptas nuestra política de privacidad y estándares de seguridad de datos.",
    onboardingContinueBtn = "Continuar",

    connectionDetailsTitle = "Detalles de la conexión",
    sessionStatsTitle = "Estadísticas de la sesión",
    serverDetailsTitle = "Datos del servidor",
    countryLabel = "País",
    uptimeLabel = "Tiempo de actividad"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    val effectiveLanguage = AppLanguage.resolveEffectiveLanguage(language)
    return when (effectiveLanguage) {
        AppLanguage.ARABIC -> ArabicStrings
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.FRENCH -> FrenchStrings
        AppLanguage.SPANISH -> SpanishStrings
        AppLanguage.SYSTEM -> EnglishStrings // Resolved above, fallback here
    }
}
